<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/phid/constants');
phutil_require_module('phabricator', 'applications/phid/storage/phid');
phutil_require_module('phabricator', 'applications/repository/storage/base');
phutil_require_module('phabricator', 'applications/repository/storage/commitdata');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorRepositoryCommit.php');
