<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/herald/adapter/base');
phutil_require_module('phabricator', 'applications/herald/storage/transcript/apply');

phutil_require_module('phutil', 'utils');


phutil_require_source('HeraldDryRunAdapter.php');
