<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/response/ajax');
phutil_require_module('phabricator', 'applications/phame/controller/base');
phutil_require_module('phabricator', 'applications/phame/storage/post');
phutil_require_module('phabricator', 'applications/phame/view/postdetail');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhamePostPreviewController.php');
