<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/audit/storage/inlinecommment');
phutil_require_module('phabricator', 'applications/repository/storage/commit');
phutil_require_module('phabricator', 'applications/repository/storage/repository');
phutil_require_module('phabricator', 'infrastructure/diff/controller');
phutil_require_module('phabricator', 'storage/queryfx');

phutil_require_module('phutil', 'utils');


phutil_require_source('DiffusionInlineCommentController.php');
