<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/response/400');
phutil_require_module('phabricator', 'aphront/response/404');
phutil_require_module('phabricator', 'aphront/response/reload');
phutil_require_module('phabricator', 'applications/flag/controller/base');
phutil_require_module('phabricator', 'applications/flag/storage/flag');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorFlagDeleteController.php');
