<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/files/engine/base');
phutil_require_module('phabricator', 'applications/files/storage/storageblob');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorMySQLFileStorageEngine.php');
