<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'parser/diff/change');

phutil_require_module('phabricator', 'applications/differential/constants/changetype');
phutil_require_module('phabricator', 'applications/differential/storage/diff');

phutil_require_module('phutil', 'utils');


phutil_require_source('DiffusionPathChange.php');
