<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infrastructure/daemon/irc/handler/base');
phutil_require_module('phabricator', 'infrastructure/env');


phutil_require_source('PhabricatorIRCObjectNameHandler.php');
