<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/sink/base');


phutil_require_source('AphrontIsolatedHTTPSink.php');
