<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/calendar/storage/base');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorCalendarHoliday.php');
