<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/repository/base');
phutil_require_module('phabricator', 'applications/repository/storage/repository');

phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPI_repository_query_Method.php');
