<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infratructure/celerity/api');
phutil_require_module('phabricator', 'infratructure/javelin/api');
phutil_require_module('phabricator', 'infratructure/javelin/markup');
phutil_require_module('phabricator', 'view/form/control/base');

phutil_require_module('phutil', 'markup');
phutil_require_module('phutil', 'utils');


phutil_require_source('AphrontFormTokenizerControl.php');
