<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/base');
phutil_require_module('phabricator', 'applications/maniphest/constants/priority');
phutil_require_module('phabricator', 'applications/maniphest/storage/auxiliary');
phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPI_maniphest_Method.php');
