<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'events/constant/type');


phutil_require_source('PhabricatorEventType.php');
