<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/differential/mail/reviewrequest');


phutil_require_source('DifferentialNewDiffMail.php');
