<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/metamta/adapter/base');
phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'future/https');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorMailImplementationSendGridAdapter.php');
