<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/project/base');
phutil_require_module('phabricator', 'applications/project/query/project');


phutil_require_source('ConduitAPI_project_query_Method.php');
