<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infratructure/celerity/api');
phutil_require_module('phabricator', 'view/base');

phutil_require_module('phutil', 'utils');


phutil_require_source('AphrontTableView.php');
