<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('aphront', 'aphront/controller');
phutil_require_module('aphront', 'aphront/response/webpage');
phutil_require_module('aphront', 'view/page/standard');

phutil_require_module('phutil', 'markup');


phutil_require_source('AphrontDefaultApplicationController.php');
