<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infrastructure/setup/storage/workflow/base');


phutil_require_source('PhabricatorStorageManagementDatabasesWorkflow.php');
