<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/response/404');
phutil_require_module('phabricator', 'applications/herald/controller/base');
phutil_require_module('phabricator', 'applications/herald/storage/rule');
phutil_require_module('phabricator', 'applications/herald/view/edithistory');
phutil_require_module('phabricator', 'applications/phid/handle/data');

phutil_require_module('phutil', 'utils');


phutil_require_source('HeraldRuleEditHistoryController.php');
