<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/drydock/blueprint/base');
phutil_require_module('phabricator', 'applications/drydock/interface/command/ssh');


phutil_require_source('DrydockRemoteHostBlueprint.php');
