<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/base');
phutil_require_module('phabricator', 'applications/differential/storage/diff');

phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPI_differential_getalldiffs_Method.php');
