<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/files/storage/file');


phutil_require_source('PhabricatorImageTransformer.php');
