<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'storage/connection/base');

phutil_require_module('phutil', 'utils');


phutil_require_source('AphrontIsolatedDatabaseConnection.php');
