<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/oauthserver/scope');
phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'parser/uri');
phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPIMethod.php');
