<?php

final class PhabricatorConpherenceRoomContextFreeGrammar
  extends PhutilContextFreeGrammar {
  protected function getRules() {
    return array(
      'start' => array(
        '[dept]',
        '[dept]',
        '[dept]',
        '[dept]',
        '[dept]',
        '[dept]',
        '[dept]',
        '[dept] ([city])',
        '[dept] ([city])',
        '[dept] - [city]',
        '[dept] - [room]',
        '[dept] / [room]',
        '[dept] [room]',
        '[city] ([dept]) - [room]',
        '[dept] ([city]) - [room]',
        '[dept] ([city]) [room]',
      ),
      'dept' => array(
        'Eng',
        'Engineering',
        'User Interface',
        'Design',
        'Data Science',
        'Database',
        'Marketing',
        'Content',
        'Ads',
        'Operations',
        'Network Ops',
        'Ops',
        'Server Ops',
        'IT',
        'Information Technology',
        'i18n',
        'Internationalization',
        'Human Resources',
        'HR',
        'Research & Development',
        'R&D',
        'Management',
        'Directors',
        'Managers',
        'Support',
        'Customer Support',
        'Finance',
        'Sales',
        'Purchasing',
        'Education',
        'Hardware Engineering',
        'Software',
        'Supply Management',
        'Logistics',
        'Growth',
        'Content Strategy',
        'Developer Relations',
        'Accounting',
        'Production',
      ),
      'city' => array(
        'Palo Alto',
        'Mtn View',
        'Cupertino',
        'Los Altos',
        'Menlo Park',
        'Santa Cruz',
        'S.F.',
        'San Francisco',
        'Seattle',
        'London',
        'New York',
        'Dublin',
        'Tokyo',
      ),
      'room' => array(
        'General',
        'Announcements',
        'Staff',
        'Interns',
        'Managers',
        'Book Club',
        'Parking',
        'Sports',
        'Social',
        'Commuting',
        'For Sale',
        'Parents@',
      ),
    );
  }
}
