<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/policy/constants/base');


phutil_require_source('PhabricatorPolicies.php');
