<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/drydock/blueprint/base');
phutil_require_module('phabricator', 'applications/drydock/constants/resourcestatus');


phutil_require_source('DrydockPhabricatorApplicationBlueprint.php');
