<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/phriction/base');
phutil_require_module('phabricator', 'applications/phriction/editor/document');

phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPI_phriction_edit_Method.php');
