<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/diffusion/query/pathid/base');
phutil_require_module('phabricator', 'infrastructure/testing/testcase');


phutil_require_source('DiffusionPathQueryTestCase.php');
