<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/files/storage/file');

phutil_require_module('phutil', 'markup');
phutil_require_module('phutil', 'markup/engine/remarkup/markuprule/base');
phutil_require_module('phutil', 'parser/simpleoptions');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorRemarkupRuleEmbedFile.php');
