<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'filesystem/deferredlog');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorAccessLog.php');
