<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/differential/exception/base');


phutil_require_source('DifferentialActionHasNoEffectException.php');
