<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/people/storage/user');

phutil_require_module('phutil', 'parser/emailaddress');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorRepositoryCommitMessageDetailParser.php');
