<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/console/plugin/base');
phutil_require_module('phabricator', 'aphront/console/plugin/xhprof/api');
phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'markup');


phutil_require_source('DarkConsoleXHProfPlugin.php');
