<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('aphront', 'aphront/response/404');
phutil_require_module('aphront', 'aphront/response/dialog');
phutil_require_module('aphront', 'aphront/response/redirect');
phutil_require_module('aphront', 'applications/directory/controller/base');
phutil_require_module('aphront', 'applications/directory/storage/category');
phutil_require_module('aphront', 'view/dialog');

phutil_require_module('phutil', 'utils');


phutil_require_source('AphrontDirectoryCategoryDeleteController.php');
