<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/base');
phutil_require_module('phabricator', 'applications/differential/parser/commitmessage');


phutil_require_source('ConduitAPI_differential_parsecommitmessage_Method.php');
