<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/audit/constants/status');


phutil_require_source('PhabricatorAuditActionConstants.php');
