<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/response/404');
phutil_require_module('phabricator', 'applications/base/controller/base');


phutil_require_source('Phabricator404Controller.php');
