<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/uiexample/examples/base');
phutil_require_module('phabricator', 'view/base');
phutil_require_module('phabricator', 'view/javelin-view');
phutil_require_module('phabricator', 'view/layout/panel');

phutil_require_module('phutil', 'markup');


phutil_require_source('JavelinViewExample.php');
phutil_require_source('JavelinViewExampleServerView.php');
