<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/diffusion/request/base');
phutil_require_module('phabricator', 'applications/repository/storage/commit');

phutil_require_module('phutil', 'utils');


phutil_require_source('DiffusionSvnRequest.php');
