<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/differential/field/selector/base');
phutil_require_module('phabricator', 'applications/differential/field/specification/applypatch');
phutil_require_module('phabricator', 'applications/differential/field/specification/arcanistproject');
phutil_require_module('phabricator', 'applications/differential/field/specification/author');
phutil_require_module('phabricator', 'applications/differential/field/specification/branch');
phutil_require_module('phabricator', 'applications/differential/field/specification/ccs');
phutil_require_module('phabricator', 'applications/differential/field/specification/commits');
phutil_require_module('phabricator', 'applications/differential/field/specification/datecreated');
phutil_require_module('phabricator', 'applications/differential/field/specification/datemodified');
phutil_require_module('phabricator', 'applications/differential/field/specification/dependencies');
phutil_require_module('phabricator', 'applications/differential/field/specification/gitsvnid');
phutil_require_module('phabricator', 'applications/differential/field/specification/host');
phutil_require_module('phabricator', 'applications/differential/field/specification/lint');
phutil_require_module('phabricator', 'applications/differential/field/specification/maniphesttasks');
phutil_require_module('phabricator', 'applications/differential/field/specification/path');
phutil_require_module('phabricator', 'applications/differential/field/specification/reviewedby');
phutil_require_module('phabricator', 'applications/differential/field/specification/reviewers');
phutil_require_module('phabricator', 'applications/differential/field/specification/revisionid');
phutil_require_module('phabricator', 'applications/differential/field/specification/revisionstatus');
phutil_require_module('phabricator', 'applications/differential/field/specification/summary');
phutil_require_module('phabricator', 'applications/differential/field/specification/testplan');
phutil_require_module('phabricator', 'applications/differential/field/specification/title');
phutil_require_module('phabricator', 'applications/differential/field/specification/unit');
phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'utils');


phutil_require_source('DifferentialDefaultFieldSelector.php');
