<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/user/base');
phutil_require_module('phabricator', 'applications/conduit/protocol/exception');
phutil_require_module('phabricator', 'applications/people/storage/userstatus');

phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPI_user_removestatus_Method.php');
