<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/differential/field/exception/validation');
phutil_require_module('phabricator', 'applications/differential/field/specification/base');
phutil_require_module('phabricator', 'view/form/control/tokenizer');

phutil_require_module('phutil', 'utils');


phutil_require_source('DifferentialReviewersFieldSpecification.php');
