<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/diffusion/request/base');
phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'future/exec');


phutil_require_source('DiffusionGitRequest.php');
