<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'error');
phutil_require_module('phutil', 'readableserializer');


phutil_require_source('DarkConsoleErrorLogPluginAPI.php');
