<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/base/storage/lisk');

phutil_require_module('phutil', 'future/exec');
phutil_require_module('phutil', 'moduleutils');


phutil_require_source('PhabricatorStorageFixtureScopeGuard.php');
