<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infrastructure/daemon/base');
phutil_require_module('phabricator', 'infrastructure/daemon/workers/storage/task');
phutil_require_module('phabricator', 'infrastructure/daemon/workers/storage/taskdata');
phutil_require_module('phabricator', 'storage/queryfx');

phutil_require_module('phutil', 'symbols');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorTaskmasterDaemon.php');
