<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infrastructure/setup/sql/base');

phutil_require_module('phutil', 'filesystem');
phutil_require_module('phutil', 'moduleutils');


phutil_require_source('PhabricatorBuiltinPatchList.php');
