<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/metamta/storage/base');
phutil_require_module('phabricator', 'applications/people/storage/preferences');
phutil_require_module('phabricator', 'applications/people/storage/user');
phutil_require_module('phabricator', 'applications/phid/handle/data');
phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'symbols');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorMetaMTAAttachment.php');
phutil_require_source('PhabricatorMetaMTAMail.php');
