<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/console/plugin/base');
phutil_require_module('phabricator', 'aphront/console/plugin/event/api');
phutil_require_module('phabricator', 'infrastructure/events/engine');
phutil_require_module('phabricator', 'view/control/table');

phutil_require_module('phutil', 'markup');


phutil_require_source('DarkConsoleEventPlugin.php');
