<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/metamta/parser');
phutil_require_module('phabricator', 'infrastructure/testing/testcase');


phutil_require_source('PhabricatorMetaMTAEmailBodyParserTestCase.php');
