<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/differential/storage/revision');
phutil_require_module('phabricator', 'infrastructure/markup/remarkup/markuprule/handle');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorRemarkupRuleDifferentialHandle.php');
