<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/base');
phutil_require_module('phabricator', 'infrastructure/daemon/storage/log');


phutil_require_source('ConduitAPI_daemon_launched_Method.php');
