<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/base');
phutil_require_module('phabricator', 'applications/diffusion/query/history/base');
phutil_require_module('phabricator', 'applications/diffusion/request/base');

phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPI_diffusion_getrecentcommitsbypath_Method.php');
