<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/drydock/blueprint/remotehost');
phutil_require_module('phabricator', 'applications/drydock/constants/resourcestatus');
phutil_require_module('phabricator', 'applications/drydock/interface/command/ssh');
phutil_require_module('phabricator', 'applications/drydock/storage/lease');
phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'future/aws/ec2');


phutil_require_source('DrydockEC2HostBlueprint.php');
