<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/paste/storage/base');
phutil_require_module('phabricator', 'applications/phid/constants');
phutil_require_module('phabricator', 'applications/phid/storage/phid');
phutil_require_module('phabricator', 'applications/policy/constants/capability');
phutil_require_module('phabricator', 'applications/policy/constants/policy');
phutil_require_module('phabricator', 'applications/policy/interface/policy');


phutil_require_source('PhabricatorPaste.php');
