<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'storage/connection/mysql/base');
phutil_require_module('phabricator', 'storage/exception/connection');


phutil_require_source('AphrontMySQLiDatabaseConnection.php');
