<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infrastructure/events/constant/type');

phutil_require_module('phutil', 'events/listener');


phutil_require_source('DarkConsoleEventPluginAPI.php');
