<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/maniphest/base');
phutil_require_module('phabricator', 'applications/maniphest/storage/transaction');

phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPI_maniphest_gettasktransactions_Method.php');
