CREATE TABLE {$NAMESPACE}_harbormaster.harbormaster_buildlintmessage (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  buildTargetPHID VARBINARY(64) NOT NULL,
  path LONGTEXT NOT NULL,
  line INT UNSIGNED,
  characterOffset INT UNSIGNED,
  code VARCHAR(32) COLLATE {$COLLATE_TEXT} NOT NULL,
  severity VARCHAR(32) COLLATE {$COLLATE_TEXT} NOT NULL,
  name VARCHAR(255) COLLATE {$COLLATE_TEXT} NOT NULL,
  properties LONGTEXT COLLATE {$COLLATE_TEXT} NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  KEY `key_target` (buildTargetPHID)
) ENGINE=INNODB, COLLATE {$COLLATE_TEXT};
