CREATE TABLE {$NAMESPACE}_token.token_token (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  name VARCHAR(64) NOT NULL COLLATE {$COLLATE_TEXT},
  flavor VARCHAR(128) NOT NULL COLLATE {$COLLATE_TEXT},
  status VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  builtinKey VARCHAR(32) COLLATE {$COLLATE_TEXT},
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  creatorPHID VARBINARY(64) NOT NULL,
  tokenImagePHID VARBINARY(64),
  UNIQUE KEY `key_phid` (phid),
  UNIQUE KEY `key_builtin` (builtinKey),
  KEY `key_creator` (creatorPHID, dateModified)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
