CREATE TABLE {$NAMESPACE}_calendar.calendar_import (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  name LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  authorPHID VARBINARY(64) NOT NULL,
  viewPolicy VARBINARY(64) NOT NULL,
  editPolicy VARBINARY(64) NOT NULL,
  engineType VARCHAR(64) NOT NULL,
  parameters LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  isDisabled BOOL NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  UNIQUE KEY `key_phid` (phid),
  KEY `key_author` (authorPHID)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
