CREATE TABLE {$NAMESPACE}_meta_data.hoststate (
  stateKey VARCHAR(128) NOT NULL COLLATE {$COLLATE_TEXT},
  stateValue LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  PRIMARY KEY (stateKey)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
