CREATE TABLE {$NAMESPACE}_nuance.nuance_importcursordata (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  sourcePHID VARBINARY(64) NOT NULL,
  cursorKey VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  cursorType VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  properties LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  UNIQUE KEY `key_phid` (phid),
  UNIQUE KEY `key_source` (sourcePHID, cursorKey)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
