CREATE TABLE {$NAMESPACE}_config.config_manualactivity (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  activityType VARCHAR(64) NOT NULL COLLATE {$COLLATE_TEXT},
  parameters LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  UNIQUE KEY `key_type` (activityType)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
