CREATE TABLE {$NAMESPACE}_packages.packages_package (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  name VARCHAR(64) NOT NULL COLLATE {$COLLATE_TEXT},
  publisherPHID VARBINARY(64) NOT NULL,
  packageKey VARCHAR(64) NOT NULL COLLATE {$COLLATE_SORT},
  viewPolicy VARBINARY(64) NOT NULL,
  editPolicy VARBINARY(64) NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  UNIQUE KEY `key_phid` (phid),
  UNIQUE KEY `key_package` (publisherPHID, packageKey)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
