CREATE TABLE {$NAMESPACE}_repository.repository_uri (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  repositoryPHID VARBINARY(64) NOT NULL,
  uri VARCHAR(255) NOT NULL COLLATE {$COLLATE_TEXT},
  builtinProtocol VARCHAR(32) COLLATE {$COLLATE_TEXT},
  builtinIdentifier VARCHAR(32) COLLATE {$COLLATE_TEXT},
  ioType VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  displayType VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  isDisabled BOOL NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  UNIQUE KEY `key_builtin` (repositoryPHID, builtinProtocol, builtinIdentifier)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
