CREATE TABLE {$NAMESPACE}_calendar.calendar_externalinvitee (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  name LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  nameIndex BINARY(12) NOT NULL,
  uri LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  parameters LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  sourcePHID VARBINARY(64) NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  UNIQUE KEY `key_name` (`nameIndex`)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
