CREATE TABLE {$NAMESPACE}_nuance.nuance_itemcommand (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  itemPHID VARBINARY(64) NOT NULL,
  authorPHID VARBINARY(64) NOT NULL,
  command VARCHAR(64) NOT NULL COLLATE {$COLLATE_TEXT},
  parameters LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  KEY `key_item` (itemPHID)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
