CREATE TABLE {$NAMESPACE}_repository.repository_gitlfsref (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  repositoryPHID VARBINARY(64) NOT NULL,
  objectHash BINARY(64) NOT NULL,
  byteSize BIGINT UNSIGNED NOT NULL,
  authorPHID VARBINARY(64) NOT NULL,
  filePHID VARBINARY(64) NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  UNIQUE KEY `key_hash` (repositoryPHID, objectHash)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
