CREATE TABLE {$NAMESPACE}_calendar.calendar_importlog (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  importPHID VARBINARY(64) NOT NULL,
  parameters LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  KEY `key_import` (`importPHID`)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
