CREATE TABLE {$NAMESPACE}_calendar.calendar_export (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  name LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  authorPHID VARBINARY(64) NOT NULL,
  policyMode VARCHAR(64) NOT NULL COLLATE {$COLLATE_TEXT},
  queryKey VARCHAR(64) NOT NULL COLLATE {$COLLATE_TEXT},
  secretKey BINARY(20) NOT NULL,
  isDisabled BOOL NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  KEY `key_author` (authorPHID),
  UNIQUE KEY `key_secret` (secretKey)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
