CREATE TABLE {$NAMESPACE}_search.search_namedqueryconfig (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  engineClassName VARCHAR(128) NOT NULL COLLATE {$COLLATE_TEXT},
  scopePHID VARBINARY(64) NOT NULL,
  properties LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL,
  UNIQUE KEY `key_scope` (engineClassName, scopePHID)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
