CREATE TABLE {$NAMESPACE}_repository.repository_refposition (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cursorID INT UNSIGNED NOT NULL,
  commitIdentifier VARCHAR(40) NOT NULL COLLATE {$COLLATE_TEXT},
  isClosed BOOL NOT NULL
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
