CREATE TABLE {$NAMESPACE}_phriction.phriction_document_fdocument (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  objectPHID VARBINARY(64) NOT NULL,
  isClosed BOOL NOT NULL,
  authorPHID VARBINARY(64),
  ownerPHID VARBINARY(64),
  epochCreated INT UNSIGNED NOT NULL,
  epochModified INT UNSIGNED NOT NULL
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
