CREATE TABLE {$NAMESPACE}_repository.repository_syncevent (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  repositoryPHID VARBINARY(64) NOT NULL,
  epoch INT UNSIGNED NOT NULL,
  devicePHID VARBINARY(64) NOT NULL,
  fromDevicePHID VARBINARY(64) NOT NULL,
  deviceVersion INT UNSIGNED,
  fromDeviceVersion INT UNSIGNED,
  resultType VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  resultCode INT UNSIGNED NOT NULL,
  syncWait BIGINT UNSIGNED NOT NULL,
  properties LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT}
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
