CREATE TABLE {$NAMESPACE}_auth.auth_password (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  objectPHID VARBINARY(64) NOT NULL,
  passwordType VARCHAR(64) NOT NULL COLLATE {$COLLATE_TEXT},
  passwordHash VARCHAR(128) NOT NULL COLLATE {$COLLATE_TEXT},
  isRevoked BOOL NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
