CREATE TABLE {$NAMESPACE}_herald.herald_webhook (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  name VARCHAR(128) NOT NULL COLLATE {$COLLATE_TEXT},
  webhookURI VARCHAR(255) NOT NULL COLLATE {$COLLATE_TEXT},
  viewPolicy VARBINARY(64) NOT NULL,
  editPolicy VARBINARY(64) NOT NULL,
  status VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  hmacKey VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
