CREATE TABLE {$NAMESPACE}_daemon.daemon_locklog (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  lockName VARCHAR(64) NOT NULL COLLATE {$COLLATE_TEXT},
  lockReleased INT UNSIGNED,
  lockParameters LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  lockContext LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
