CREATE TABLE {$NAMESPACE}_auth.auth_challenge (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  userPHID VARBINARY(64) NOT NULL,
  factorPHID VARBINARY(64) NOT NULL,
  sessionPHID VARBINARY(64) NOT NULL,
  challengeKey VARCHAR(255) NOT NULL COLLATE {$COLLATE_TEXT},
  challengeTTL INT UNSIGNED NOT NULL,
  properties LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
