CREATE TABLE {$NAMESPACE}_fact.fact_keydimension (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  factKey VARCHAR(64) NOT NULL COLLATE {$COLLATE_TEXT},
  UNIQUE KEY `key_factkey` (factKey)
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
