CREATE TABLE {$NAMESPACE}_fact.fact_intdatapoint (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  keyID INT UNSIGNED NOT NULL,
  objectID INT UNSIGNED NOT NULL,
  dimensionID INT UNSIGNED,
  value BIGINT SIGNED NOT NULL,
  epoch INT UNSIGNED NOT NULL
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
