CREATE TABLE {$NAMESPACE}_herald.herald_webhookrequest (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  webhookPHID VARBINARY(64) NOT NULL,
  objectPHID VARBINARY(64) NOT NULL,
  status VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  properties LONGTEXT NOT NULL COLLATE {$COLLATE_TEXT},
  lastRequestResult VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  lastRequestEpoch INT UNSIGNED NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
