CREATE TABLE {$NAMESPACE}_user.user_externalaccountidentifier (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phid VARBINARY(64) NOT NULL,
  externalAccountPHID VARBINARY(64) NOT NULL,
  providerConfigPHID VARBINARY(64) NOT NULL,
  identifierHash BINARY(12) NOT NULL,
  identifierRaw LONGTEXT NOT NULL,
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET={$CHARSET} COLLATE {$COLLATE_TEXT};
