CREATE TABLE {$NAMESPACE}_file.file_attachment (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  objectPHID VARBINARY(64) NOT NULL,
  filePHID VARBINARY(64) NOT NULL,
  attacherPHID VARBINARY(64),
  attachmentMode VARCHAR(32) NOT NULL COLLATE {$COLLATE_TEXT},
  dateCreated INT UNSIGNED NOT NULL,
  dateModified INT UNSIGNED NOT NULL
) ENGINE=InnoDB, COLLATE {$COLLATE_TEXT};
