<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/repository/daemon/commitdiscovery/base');
phutil_require_module('phabricator', 'applications/repository/storage/commit');
phutil_require_module('phabricator', 'applications/timeline/storage/event');

phutil_require_module('phutil', 'future/exec');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorRepositoryGitCommitDiscoveryDaemon.php');
