<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/metamta/adapter/base');

phutil_require_module('phutil', 'moduleutils');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorMailImplementationPHPMailerLiteAdapter.php');
