<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'events/event');


phutil_require_source('PhabricatorEvent.php');
