<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infrastructure/env');
phutil_require_module('phabricator', 'view/form/control/base');

phutil_require_module('phutil', 'moduleutils');


phutil_require_source('AphrontFormRecaptchaControl.php');
