<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/repository/constants/repositorytype');
phutil_require_module('phabricator', 'applications/repository/daemon/base');

phutil_require_module('phutil', 'filesystem');
phutil_require_module('phutil', 'future/exec');


phutil_require_source('PhabricatorRepositoryPullLocalDaemon.php');
