<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/response/404');
phutil_require_module('phabricator', 'applications/people/storage/user');
phutil_require_module('phabricator', 'applications/phame/controller/base');
phutil_require_module('phabricator', 'applications/phame/query/post');
phutil_require_module('phabricator', 'applications/phame/storage/post');
phutil_require_module('phabricator', 'applications/phame/view/postlist');
phutil_require_module('phabricator', 'view/control/pager');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhamePostListBaseController.php');
