<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infrastructure/query/base');
phutil_require_module('phabricator', 'storage/qsprintf');


phutil_require_source('PhabricatorOffsetPagedQuery.php');
