<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/drydock/interface/webroot/base');


phutil_require_source('DrydockApacheWebrootInterface.php');
