<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/maniphest/auxiliaryfield/base');
phutil_require_module('phabricator', 'applications/maniphest/auxiliaryfield/typeexception');
phutil_require_module('phabricator', 'applications/maniphest/auxiliaryfield/validationexception');
phutil_require_module('phabricator', 'view/form/control/select');
phutil_require_module('phabricator', 'view/form/control/text');


phutil_require_source('ManiphestAuxiliaryFieldDefaultSpecification.php');
