<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/people/storage/user');
phutil_require_module('phabricator', 'infrastructure/testing/testcase');
phutil_require_module('phabricator', 'view/utils');


phutil_require_source('PhabricatorLocalTimeTestCase.php');
phutil_require_source('PhabricatorUnitsTestCase.php');
