<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/diffusion/data/pathchange');
phutil_require_module('phabricator', 'applications/diffusion/query/history/base');

phutil_require_module('phutil', 'future/exec');


phutil_require_source('DiffusionGitHistoryQuery.php');
