<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/drydock/blueprint/base');
phutil_require_module('phabricator', 'applications/drydock/constants/resourcestatus');
phutil_require_module('phabricator', 'applications/drydock/interface/webroot/apache');
phutil_require_module('phabricator', 'applications/drydock/storage/lease');

phutil_require_module('phutil', 'filesystem');
phutil_require_module('phutil', 'utils');
phutil_require_module('phutil', 'xsprintf/csprintf');


phutil_require_source('DrydockApacheWebrootBlueprint.php');
