<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'lint/linter/xhpast/naminghook');


phutil_require_source('PhabricatorSymbolNameLinter.php');
