<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/diffusion/query/lastmodified/base');
phutil_require_module('phabricator', 'applications/repository/constants/repositorytype');

phutil_require_module('phutil', 'symbols');


phutil_require_source('DiffusionDiffQuery.php');
