<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'storage/exception/parameter');

phutil_require_module('phutil', 'xsprintf');


phutil_require_source('qsprintf.php');
