<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/response/404');
phutil_require_module('phabricator', 'applications/files/storage/file');
phutil_require_module('phabricator', 'applications/xhprof/controller/base');
phutil_require_module('phabricator', 'applications/xhprof/view/symbol');
phutil_require_module('phabricator', 'applications/xhprof/view/toplevel');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorXHProfProfileController.php');
