<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/audit/constants/status');
phutil_require_module('phabricator', 'view/base');
phutil_require_module('phabricator', 'view/control/table');

phutil_require_module('phutil', 'markup');
phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorAuditListView.php');
