<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'storage/exception/base');


phutil_require_source('AphrontQuerySchemaException.php');
