<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('aphront', 'view/form/control/base');

phutil_require_module('phutil', 'markup');


phutil_require_source('AphrontFormSubmitControl.php');
