<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/audit/storage/base');
phutil_require_module('phabricator', 'applications/phid/storage/phid');


phutil_require_source('PhabricatorAuditComment.php');
