<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/storage/lisk');


phutil_require_source('AphrontDirectoryDAO.php');
