<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/daemon/controller/base');
phutil_require_module('phabricator', 'applications/daemon/view/daemonlogevents');
phutil_require_module('phabricator', 'infrastructure/daemon/storage/event');
phutil_require_module('phabricator', 'view/control/pager');
phutil_require_module('phabricator', 'view/layout/panel');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorDaemonCombinedLogController.php');
