<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'infrastructure/env');

phutil_require_module('phutil', 'markup/syntax/engine/default');


phutil_require_source('PhabricatorSyntaxHighlighter.php');
