<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/phid/storage/phid');
phutil_require_module('phabricator', 'infrastructure/testing/testcase');
phutil_require_module('phabricator', 'storage/connection/isolated');
phutil_require_module('phabricator', 'storage/queryfx');

phutil_require_module('phutil', 'filesystem');
phutil_require_module('phutil', 'utils');


phutil_require_source('AphrontIsolatedDatabaseConnectionTestCase.php');
