<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/maniphest/controller/descriptionchange');


phutil_require_source('ManiphestTaskDescriptionDiffController.php');
