<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/conduit/method/base');
phutil_require_module('phabricator', 'applications/conduit/protocol/exception');
phutil_require_module('phabricator', 'applications/feed/query');
phutil_require_module('phabricator', 'applications/phid/handle/data');

phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPI_feed_query_Method.php');
