<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/search/storage/base');
phutil_require_module('phabricator', 'applications/search/storage/document/field');
phutil_require_module('phabricator', 'applications/search/storage/document/relationship');
phutil_require_module('phabricator', 'storage/qsprintf');
phutil_require_module('phabricator', 'storage/queryfx');


phutil_require_source('PhabricatorSearchDocument.php');
