<?php

/**
 * This file is automatically generated. Use 'celerity_mapper.php' to rebuild
 * it.
 * @generated
 */

celerity_register_resource_map(array(
  'aphront-attached-file-view-css' =>
  array(
    'uri' => '/res/a6ca5487/rsrc/css/aphront/attached-file-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/attached-file-view.css',
  ),
  'aphront-calendar-view-css' =>
  array(
    'uri' => '/res/c86d9a4b/rsrc/css/aphront/calendar-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/calendar-view.css',
  ),
  'aphront-contextbar-view-css' =>
  array(
    'uri' => '/res/3e2f3045/rsrc/css/aphront/context-bar.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/context-bar.css',
  ),
  'aphront-crumbs-view-css' =>
  array(
    'uri' => '/res/9009e6bd/rsrc/css/aphront/crumbs-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/crumbs-view.css',
  ),
  'aphront-dark-console-css' =>
  array(
    'uri' => '/res/1a9f84bb/rsrc/css/aphront/dark-console.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/dark-console.css',
  ),
  'aphront-dialog-view-css' =>
  array(
    'uri' => '/res/1c0a5f75/rsrc/css/aphront/dialog-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/dialog-view.css',
  ),
  'aphront-error-view-css' =>
  array(
    'uri' => '/res/e4c5e4ed/rsrc/css/aphront/error-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/error-view.css',
  ),
  'aphront-form-view-css' =>
  array(
    'uri' => '/res/16af59d8/rsrc/css/aphront/form-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/form-view.css',
  ),
  'aphront-headsup-action-list-view-css' =>
  array(
    'uri' => '/res/84743e20/rsrc/css/aphront/headsup-action-list-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/headsup-action-list-view.css',
  ),
  'aphront-list-filter-view-css' =>
  array(
    'uri' => '/res/0f5ddaba/rsrc/css/aphront/list-filter-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/list-filter-view.css',
  ),
  'aphront-pager-view-css' =>
  array(
    'uri' => '/res/43fb79f0/rsrc/css/aphront/pager-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/pager-view.css',
  ),
  'aphront-panel-view-css' =>
  array(
    'uri' => '/res/58da9c70/rsrc/css/aphront/panel-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/panel-view.css',
  ),
  'aphront-request-failure-view-css' =>
  array(
    'uri' => '/res/c9a43002/rsrc/css/aphront/request-failure-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/request-failure-view.css',
  ),
  'aphront-side-nav-view-css' =>
  array(
    'uri' => '/res/f92966bd/rsrc/css/aphront/side-nav-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/side-nav-view.css',
  ),
  'aphront-table-view-css' =>
  array(
    'uri' => '/res/f4f39a2e/rsrc/css/aphront/table-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/table-view.css',
  ),
  'aphront-tokenizer-control-css' =>
  array(
    'uri' => '/res/f530af47/rsrc/css/aphront/tokenizer.css',
    'type' => 'css',
    'requires' =>
    array(
      0 => 'aphront-typeahead-control-css',
    ),
    'disk' => '/rsrc/css/aphront/tokenizer.css',
  ),
  'aphront-typeahead-control-css' =>
  array(
    'uri' => '/res/a05236a6/rsrc/css/aphront/typeahead.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/typeahead.css',
  ),
  'differential-changeset-view-css' =>
  array(
    'uri' => '/res/be4f9b2a/rsrc/css/application/differential/changeset-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/changeset-view.css',
  ),
  'differential-core-view-css' =>
  array(
    'uri' => '/res/584d40e8/rsrc/css/application/differential/core.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/core.css',
  ),
  'differential-inline-comment-editor' =>
  array(
    'uri' => '/res/ff5f42a9/rsrc/js/application/differential/DifferentialInlineCommentEditor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-dom',
      1 => 'javelin-workflow',
      2 => 'javelin-util',
      3 => 'javelin-stratcom',
      4 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/application/differential/DifferentialInlineCommentEditor.js',
  ),
  'differential-local-commits-view-css' =>
  array(
    'uri' => '/res/8cdacd82/rsrc/css/application/differential/local-commits-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/local-commits-view.css',
  ),
  'differential-revision-add-comment-css' =>
  array(
    'uri' => '/res/849748d3/rsrc/css/application/differential/add-comment.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/add-comment.css',
  ),
  'files-css' =>
  array(
    'uri' => '/res/a265a77d/rsrc/css/application/files/files.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/files/files.css',
  ),
  'herald-css' =>
  array(
    'uri' => '/res/5051f3ab/rsrc/css/application/herald/herald.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/herald/herald.css',
  ),
  'herald-test-css' =>
  array(
    'uri' => '/res/c0cd6bdb/rsrc/css/application/herald/herald-test.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/herald/herald-test.css',
  ),
  'javelin-behavior' =>
  array(
    'uri' => '/res/0017f840/rsrc/js/javelin/lib/behavior.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-magical-init',
    ),
    'disk' => '/rsrc/js/javelin/lib/behavior.js',
  ),
  'javelin-behavior-aphront-basic-tokenizer' =>
  array(
    'uri' => '/res/9be30797/rsrc/js/application/core/behavior-tokenizer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-typeahead',
      2 => 'javelin-tokenizer',
      3 => 'javelin-typeahead-preloaded-source',
      4 => 'javelin-typeahead-ondemand-source',
      5 => 'javelin-dom',
      6 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-tokenizer.js',
  ),
  'javelin-behavior-aphront-drag-and-drop' =>
  array(
    'uri' => '/res/ac21045a/rsrc/js/application/core/behavior-drag-and-drop.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
      3 => 'phabricator-drag-and-drop-file-upload',
    ),
    'disk' => '/rsrc/js/application/core/behavior-drag-and-drop.js',
  ),
  'javelin-behavior-aphront-drag-and-drop-textarea' =>
  array(
    'uri' => '/res/fa7527f9/rsrc/js/application/core/behavior-drag-and-drop-textarea.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'phabricator-drag-and-drop-file-upload',
    ),
    'disk' => '/rsrc/js/application/core/behavior-drag-and-drop-textarea.js',
  ),
  'javelin-behavior-aphront-form-disable-on-submit' =>
  array(
    'uri' => '/res/6c659ede/rsrc/js/application/core/behavior-form.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-form.js',
  ),
  'javelin-behavior-countdown-timer' =>
  array(
    'uri' => '/res/5ee9cb13/rsrc/js/application/countdown/timer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/countdown/timer.js',
  ),
  0 =>
  array(
    'uri' => '/res/b6096fdd/rsrc/js/javelin/lib/__tests__/URI.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-uri',
      1 => 'javelin-php-serializer',
    ),
    'disk' => '/rsrc/js/javelin/lib/__tests__/URI.js',
  ),
  'differential-revision-comment-css' =>
  array(
    'uri' => '/res/9fb8013b/rsrc/css/application/differential/revision-comment.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/revision-comment.css',
  ),
  'differential-revision-comment-list-css' =>
  array(
    'uri' => '/res/3b31faa3/rsrc/css/application/differential/revision-comment-list.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/revision-comment-list.css',
  ),
  'differential-revision-detail-css' =>
  array(
    'uri' => '/res/33592453/rsrc/css/application/differential/revision-detail.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/revision-detail.css',
  ),
  'differential-revision-history-css' =>
  array(
    'uri' => '/res/0d7d515d/rsrc/css/application/differential/revision-history.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/revision-history.css',
  ),
  'differential-table-of-contents-css' =>
  array(
    'uri' => '/res/d173445b/rsrc/css/application/differential/table-of-contents.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/table-of-contents.css',
  ),
  'diffusion-commit-view-css' =>
  array(
    'uri' => '/res/bc39d876/rsrc/css/application/diffusion/commit-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/diffusion/commit-view.css',
  ),
  'diffusion-source-css' =>
  array(
    'uri' => '/res/db4566b6/rsrc/css/application/diffusion/diffusion-source.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/diffusion/diffusion-source.css',
  ),
  'herald-rule-editor' =>
  array(
    'uri' => '/res/4d6dff2b/rsrc/js/application/herald/HeraldRuleEditor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'multirow-row-manager',
      1 => 'javelin-install',
      2 => 'javelin-typeahead',
      3 => 'javelin-util',
      4 => 'javelin-dom',
      5 => 'javelin-tokenizer',
      6 => 'javelin-typeahead-preloaded-source',
      7 => 'javelin-stratcom',
      8 => 'javelin-json',
      9 => 'phabricator-prefab',
    ),
    'disk' => '/rsrc/js/application/herald/HeraldRuleEditor.js',
  ),
  'javelin-behavior-dark-console' =>
  array(
    'uri' => '/res/c80156c4/rsrc/js/application/core/behavior-dark-console.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-request',
      5 => 'phabricator-keyboard-shortcut',
    ),
    'disk' => '/rsrc/js/application/core/behavior-dark-console.js',
  ),
  'javelin-behavior-differential-accept-with-errors' =>
  array(
    'uri' => '/res/41c4685b/rsrc/js/application/differential/behavior-accept-with-errors.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-accept-with-errors.js',
  ),
  'javelin-behavior-differential-add-reviewers-and-ccs' =>
  array(
    'uri' => '/res/c306ae14/rsrc/js/application/differential/behavior-add-reviewers-and-ccs.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-tokenizer',
      3 => 'javelin-typeahead',
      4 => 'javelin-typeahead-preloaded-source',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-add-reviewers-and-ccs.js',
  ),
  'javelin-behavior-differential-comment-jump' =>
  array(
    'uri' => '/res/be77fced/rsrc/js/application/differential/behavior-comment-jump.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-util',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-comment-jump.js',
  ),
  'javelin-behavior-differential-diff-radios' =>
  array(
    'uri' => '/res/004cb66f/rsrc/js/application/differential/behavior-diff-radios.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-diff-radios.js',
  ),
  'javelin-behavior-differential-edit-inline-comments' =>
  array(
    'uri' => '/res/b1168479/rsrc/js/application/differential/behavior-edit-inline-comments.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
      3 => 'javelin-util',
      4 => 'javelin-vector',
      5 => 'differential-inline-comment-editor',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-edit-inline-comments.js',
  ),
  'javelin-behavior-differential-feedback-preview' =>
  array(
    'uri' => '/res/89633315/rsrc/js/application/differential/behavior-comment-preview.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
      3 => 'javelin-request',
      4 => 'javelin-util',
      5 => 'phabricator-shaped-request',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-comment-preview.js',
  ),
  'javelin-behavior-differential-keyboard-navigation' =>
  array(
    'uri' => '/res/e36415a2/rsrc/js/application/differential/behavior-keyboard-nav.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'phabricator-keyboard-shortcut',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-keyboard-nav.js',
  ),
  'javelin-behavior-differential-populate' =>
  array(
    'uri' => '/res/6efe5cd2/rsrc/js/application/differential/behavior-populate.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-workflow',
      2 => 'javelin-util',
      3 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-populate.js',
  ),
  'javelin-behavior-differential-show-all-comments' =>
  array(
    'uri' => '/res/bcc990f0/rsrc/js/application/differential/behavior-show-all-comments.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-show-all-comments.js',
  ),
  'javelin-behavior-differential-show-more' =>
  array(
    'uri' => '/res/eaaccd7a/rsrc/js/application/differential/behavior-show-more.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-workflow',
      3 => 'javelin-util',
      4 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-show-more.js',
  ),
  'javelin-behavior-diffusion-jump-to' =>
  array(
    'uri' => '/res/7c42e1ba/rsrc/js/application/diffusion/behavior-jump-to.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-util',
      2 => 'javelin-vector',
      3 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/diffusion/behavior-jump-to.js',
  ),
  'javelin-behavior-diffusion-pull-lastmodified' =>
  array(
    'uri' => '/res/29fe2790/rsrc/js/application/diffusion/behavior-pull-lastmodified.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
      3 => 'javelin-request',
    ),
    'disk' => '/rsrc/js/application/diffusion/behavior-pull-lastmodified.js',
  ),
  'javelin-behavior-error-log' =>
  array(
    'uri' => '/res/a5cb42a5/rsrc/js/application/core/behavior-error-log.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-error-log.js',
  ),
  'javelin-behavior-files-drag-and-drop' =>
  array(
    'uri' => '/res/0e84cc42/rsrc/js/application/core/behavior-files-drag-and-drop.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-uri',
      3 => 'phabricator-drag-and-drop-file-upload',
    ),
    'disk' => '/rsrc/js/application/core/behavior-files-drag-and-drop.js',
  ),
  'javelin-behavior-herald-rule-editor' =>
  array(
    'uri' => '/res/77a0c945/rsrc/js/application/herald/herald-rule-editor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'herald-rule-editor',
      1 => 'javelin-behavior',
    ),
    'disk' => '/rsrc/js/application/herald/herald-rule-editor.js',
  ),
  'javelin-behavior-maniphest-project-create' =>
  array(
    'uri' => '/res/85a0eaf9/rsrc/js/application/maniphest/behavior-project-create.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-stratcom',
      3 => 'javelin-workflow',
    ),
    'disk' => '/rsrc/js/application/maniphest/behavior-project-create.js',
  ),
  'javelin-behavior-maniphest-transaction-controls' =>
  array(
    'uri' => '/res/33bd237a/rsrc/js/application/maniphest/behavior-transaction-controls.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-tokenizer',
      3 => 'javelin-typeahead',
      4 => 'javelin-typeahead-preloaded-source',
    ),
    'disk' => '/rsrc/js/application/maniphest/behavior-transaction-controls.js',
  ),
  'javelin-behavior-maniphest-transaction-expand' =>
  array(
    'uri' => '/res/966410de/rsrc/js/application/maniphest/behavior-transaction-expand.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-workflow',
      3 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/application/maniphest/behavior-transaction-expand.js',
  ),
  'javelin-behavior-maniphest-transaction-preview' =>
  array(
    'uri' => '/res/44e86555/rsrc/js/application/maniphest/behavior-transaction-preview.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
      3 => 'phabricator-shaped-request',
    ),
    'disk' => '/rsrc/js/application/maniphest/behavior-transaction-preview.js',
  ),
  'javelin-behavior-owners-path-editor' =>
  array(
    'uri' => '/res/9cf78ffc/rsrc/js/application/owners/owners-path-editor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'owners-path-editor',
      1 => 'javelin-behavior',
    ),
    'disk' => '/rsrc/js/application/owners/owners-path-editor.js',
  ),
  'javelin-behavior-phabricator-keyboard-pager' =>
  array(
    'uri' => '/res/56d64eff/rsrc/js/application/core/behavior-keyboard-pager.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-uri',
      2 => 'phabricator-keyboard-shortcut',
    ),
    'disk' => '/rsrc/js/application/core/behavior-keyboard-pager.js',
  ),
  'javelin-behavior-phabricator-keyboard-shortcuts' =>
  array(
    'uri' => '/res/94b009e2/rsrc/js/application/core/behavior-keyboard-shortcuts.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-workflow',
      2 => 'javelin-json',
      3 => 'phabricator-keyboard-shortcut',
    ),
    'disk' => '/rsrc/js/application/core/behavior-keyboard-shortcuts.js',
  ),
  'javelin-behavior-phabricator-object-selector' =>
  array(
    'uri' => '/res/1f7867ca/rsrc/js/application/core/behavior-object-selector.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-request',
      3 => 'javelin-util',
      4 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-object-selector.js',
  ),
  'javelin-behavior-phabricator-watch-anchor' =>
  array(
    'uri' => '/res/96f40736/rsrc/js/application/core/behavior-watch-anchor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-watch-anchor.js',
  ),
  'javelin-behavior-phriction-document-preview' =>
  array(
    'uri' => '/res/f1665ecd/rsrc/js/application/phriction/phriction-document-preview.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
      3 => 'phabricator-shaped-request',
    ),
    'disk' => '/rsrc/js/application/phriction/phriction-document-preview.js',
  ),
  'javelin-behavior-projects-resource-editor' =>
  array(
    'uri' => '/res/ffdde7d9/rsrc/js/application/projects/projects-resource-editor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'phabricator-prefab',
      2 => 'multirow-row-manager',
      3 => 'javelin-tokenizer',
      4 => 'javelin-typeahead-preloaded-source',
      5 => 'javelin-typeahead',
      6 => 'javelin-dom',
      7 => 'javelin-json',
      8 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/projects/projects-resource-editor.js',
  ),
  'javelin-behavior-refresh-csrf' =>
  array(
    'uri' => '/res/88beba4c/rsrc/js/application/core/behavior-refresh-csrf.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-request',
      1 => 'javelin-behavior',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-refresh-csrf.js',
  ),
  'javelin-behavior-repository-crossreference' =>
  array(
    'uri' => '/res/49472f48/rsrc/js/application/repository/repository-crossreference.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-uri',
    ),
    'disk' => '/rsrc/js/application/repository/repository-crossreference.js',
  ),
  'javelin-behavior-view-placeholder' =>
  array(
    'uri' => '/res/5b89bdf5/rsrc/js/javelin/ext/view/ViewPlaceholder.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-view-renderer',
    ),
    'disk' => '/rsrc/js/javelin/ext/view/ViewPlaceholder.js',
  ),
  'javelin-behavior-workflow' =>
  array(
    'uri' => '/res/079f49c3/rsrc/js/application/core/behavior-workflow.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-workflow',
    ),
    'disk' => '/rsrc/js/application/core/behavior-workflow.js',
  ),
  'javelin-color' =>
  array(
    'uri' => '/res/b0439fc9/rsrc/js/javelin/ext/fx/Color.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/ext/fx/Color.js',
  ),
  'javelin-cookie' =>
  array(
    'uri' => '/res/a9cddab0/rsrc/js/javelin/lib/Cookie.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/lib/Cookie.js',
  ),
  'javelin-dom' =>
  array(
    'uri' => '/res/b2e8a5b6/rsrc/js/javelin/lib/DOM.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-magical-init',
      1 => 'javelin-install',
      2 => 'javelin-util',
      3 => 'javelin-vector',
      4 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/javelin/lib/DOM.js',
  ),
  'javelin-dynval' =>
  array(
    'uri' => '/res/d89c6f88/rsrc/js/javelin/ext/reactor/core/DynVal.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-reactornode',
      2 => 'javelin-util',
      3 => 'javelin-reactor',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/core/DynVal.js',
  ),
  'javelin-event' =>
  array(
    'uri' => '/res/f42fa6ea/rsrc/js/javelin/core/Event.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/core/Event.js',
  ),
  'javelin-fx' =>
  array(
    'uri' => '/res/97e25a7f/rsrc/js/javelin/ext/fx/FX.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-color',
      1 => 'javelin-install',
      2 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/fx/FX.js',
  ),
  'javelin-history' =>
  array(
    'uri' => '/res/9bb36651/rsrc/js/javelin/lib/History.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-stratcom',
      1 => 'javelin-install',
      2 => 'javelin-uri',
      3 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/lib/History.js',
  ),
  'javelin-install' =>
  array(
    'uri' => '/res/cab679ff/rsrc/js/javelin/core/install.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-util',
      1 => 'javelin-magical-init',
    ),
    'disk' => '/rsrc/js/javelin/core/install.js',
  ),
  'javelin-json' =>
  array(
    'uri' => '/res/561b8056/rsrc/js/javelin/lib/JSON.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/lib/JSON.js',
  ),
  'javelin-magical-init' =>
  array(
    'uri' => '/res/0e72d59b/rsrc/js/javelin/core/init.js',
    'type' => 'js',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/js/javelin/core/init.js',
  ),
  'javelin-mask' =>
  array(
    'uri' => '/res/03ef78b8/rsrc/js/javelin/lib/Mask.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-vector',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/javelin/lib/Mask.js',
  ),
  'javelin-reactor' =>
  array(
    'uri' => '/res/dfd87f3c/rsrc/js/javelin/ext/reactor/core/Reactor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/core/Reactor.js',
  ),
  'javelin-reactor-dom' =>
  array(
    'uri' => '/res/701b6f39/rsrc/js/javelin/ext/reactor/dom/RDOM.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-dom',
      1 => 'javelin-dynval',
      2 => 'javelin-reactornode',
      3 => 'javelin-install',
      4 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/dom/RDOM.js',
  ),
  'javelin-reactor-node-calmer' =>
  array(
    'uri' => '/res/5a35920a/rsrc/js/javelin/ext/reactor/core/ReactorNodeCalmer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-reactor',
      2 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/core/ReactorNodeCalmer.js',
  ),
  'javelin-reactornode' =>
  array(
    'uri' => '/res/f278cc27/rsrc/js/javelin/ext/reactor/core/ReactorNode.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-reactor',
      2 => 'javelin-util',
      3 => 'javelin-reactor-node-calmer',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/core/ReactorNode.js',
  ),
  'javelin-request' =>
  array(
    'uri' => '/res/b3257b7d/rsrc/js/javelin/lib/Request.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-stratcom',
      2 => 'javelin-util',
      3 => 'javelin-behavior',
      4 => 'javelin-json',
      5 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/javelin/lib/Request.js',
  ),
  'javelin-resource' =>
  array(
    'uri' => '/res/1ebc5a0d/rsrc/js/javelin/lib/Resource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-magical-init',
      1 => 'javelin-stratcom',
      2 => 'javelin-util',
      3 => 'javelin-uri',
    ),
    'disk' => '/rsrc/js/javelin/lib/Resource.js',
  ),
  'javelin-stratcom' =>
  array(
    'uri' => '/res/d7a3d1e9/rsrc/js/javelin/core/Stratcom.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-event',
      2 => 'javelin-util',
      3 => 'javelin-magical-init',
    ),
    'disk' => '/rsrc/js/javelin/core/Stratcom.js',
  ),
  'javelin-tokenizer' =>
  array(
    'uri' => '/res/5b541fb2/rsrc/js/javelin/lib/control/tokenizer/Tokenizer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-dom',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
      3 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/tokenizer/Tokenizer.js',
  ),
  'javelin-typeahead' =>
  array(
    'uri' => '/res/7dea2b98/rsrc/js/javelin/lib/control/typeahead/Typeahead.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-dom',
      2 => 'javelin-vector',
      3 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/Typeahead.js',
  ),
  'javelin-typeahead-composite-source' =>
  array(
    'uri' => '/res/7c0d631f/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadCompositeSource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-typeahead-source',
      2 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadCompositeSource.js',
  ),
  'javelin-typeahead-normalizer' =>
  array(
    'uri' => '/res/a9e97c0d/rsrc/js/javelin/lib/control/typeahead/normalizer/TypeaheadNormalizer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/normalizer/TypeaheadNormalizer.js',
  ),
  'javelin-typeahead-ondemand-source' =>
  array(
    'uri' => '/res/81e531aa/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadOnDemandSource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
      3 => 'javelin-request',
      4 => 'javelin-typeahead-source',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadOnDemandSource.js',
  ),
  'javelin-typeahead-preloaded-source' =>
  array(
    'uri' => '/res/d464efd2/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadPreloadedSource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
      3 => 'javelin-request',
      4 => 'javelin-typeahead-source',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadPreloadedSource.js',
  ),
  'javelin-typeahead-source' =>
  array(
    'uri' => '/res/8606f519/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadSource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-dom',
      3 => 'javelin-typeahead-normalizer',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadSource.js',
  ),
  'javelin-uri' =>
  array(
    'uri' => '/res/393ace00/rsrc/js/javelin/lib/URI.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/javelin/lib/URI.js',
  ),
  'javelin-util' =>
  array(
    'uri' => '/res/2180bc95/rsrc/js/javelin/core/util.js',
    'type' => 'js',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/js/javelin/core/util.js',
  ),
  'javelin-vector' =>
  array(
    'uri' => '/res/50535cb8/rsrc/js/javelin/lib/Vector.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-event',
    ),
    'disk' => '/rsrc/js/javelin/lib/Vector.js',
  ),
  'javelin-view' =>
  array(
    'uri' => '/res/b98657a7/rsrc/js/javelin/ext/view/View.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/view/View.js',
  ),
  'javelin-view-html' =>
  array(
    'uri' => '/res/7e5a2122/rsrc/js/javelin/ext/view/HTMLView.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
    ),
    'disk' => '/rsrc/js/javelin/ext/view/HTMLView.js',
  ),
  'javelin-view-interpreter' =>
  array(
    'uri' => '/res/17e911ca/rsrc/js/javelin/ext/view/ViewInterpreter.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-view',
      1 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/ext/view/ViewInterpreter.js',
  ),
  'javelin-view-renderer' =>
  array(
    'uri' => '/res/db4ed5a2/rsrc/js/javelin/ext/view/ViewRenderer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/ext/view/ViewRenderer.js',
  ),
  'javelin-view-visitor' =>
  array(
    'uri' => '/res/0ef9dc43/rsrc/js/javelin/ext/view/ViewVisitor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/view/ViewVisitor.js',
  ),
  'javelin-workflow' =>
  array(
    'uri' => '/res/519c4e1a/rsrc/js/javelin/lib/Workflow.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-stratcom',
      1 => 'javelin-request',
      2 => 'javelin-dom',
      3 => 'javelin-vector',
      4 => 'javelin-install',
      5 => 'javelin-util',
      6 => 'javelin-mask',
      7 => 'javelin-uri',
    ),
    'disk' => '/rsrc/js/javelin/lib/Workflow.js',
  ),
  'mainphest-task-detail-css' =>
  array(
    'uri' => '/res/8cf452e0/rsrc/css/application/maniphest/task-detail.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/maniphest/task-detail.css',
  ),
  'maniphest-task-summary-css' =>
  array(
    'uri' => '/res/14cb4b5d/rsrc/css/application/maniphest/task-summary.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/maniphest/task-summary.css',
  ),
  'maniphest-transaction-detail-css' =>
  array(
    'uri' => '/res/149fccab/rsrc/css/application/maniphest/transaction-detail.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/maniphest/transaction-detail.css',
  ),
  'multirow-row-manager' =>
  array(
    'uri' => '/res/0a9b3dee/rsrc/js/application/core/MultirowRowManager.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
      3 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/core/MultirowRowManager.js',
  ),
  'owners-path-editor' =>
  array(
    'uri' => '/res/e6c51eb6/rsrc/js/application/owners/OwnersPathEditor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'multirow-row-manager',
      1 => 'javelin-install',
      2 => 'path-typeahead',
      3 => 'javelin-dom',
      4 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/owners/OwnersPathEditor.js',
  ),
  'owners-path-editor-css' =>
  array(
    'uri' => '/res/9bc5332c/rsrc/css/application/owners/owners-path-editor.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/owners/owners-path-editor.css',
  ),
  'path-typeahead' =>
  array(
    'uri' => '/res/50246fb6/rsrc/js/application/herald/PathTypeahead.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-typeahead',
      2 => 'javelin-dom',
      3 => 'javelin-request',
      4 => 'javelin-typeahead-ondemand-source',
      5 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/herald/PathTypeahead.js',
  ),
  'phabricator-content-source-view-css' =>
  array(
    'uri' => '/res/8c738a93/rsrc/css/application/contentsource/content-source-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/contentsource/content-source-view.css',
  ),
  'phabricator-core-buttons-css' =>
  array(
    'uri' => '/res/3059cf79/rsrc/css/core/buttons.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/core/buttons.css',
  ),
  'phabricator-core-css' =>
  array(
    'uri' => '/res/bd20d04b/rsrc/css/core/core.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/core/core.css',
  ),
  'phabricator-countdown-css' =>
  array(
    'uri' => '/res/0f646281/rsrc/css/application/countdown/timer.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/countdown/timer.css',
  ),
  'phabricator-directory-css' =>
  array(
    'uri' => '/res/a3d307c5/rsrc/css/application/directory/phabricator-directory.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/directory/phabricator-directory.css',
  ),
  'phabricator-drag-and-drop-file-upload' =>
  array(
    'uri' => '/res/63a06ad9/rsrc/js/application/core/DragAndDropFileUpload.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-request',
      3 => 'javelin-dom',
      4 => 'javelin-uri',
    ),
    'disk' => '/rsrc/js/application/core/DragAndDropFileUpload.js',
  ),
  'phabricator-feed-css' =>
  array(
    'uri' => '/res/32e5879b/rsrc/css/application/feed/feed.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/feed/feed.css',
  ),
  'phabricator-keyboard-shortcut' =>
  array(
    'uri' => '/res/beed38cd/rsrc/js/application/core/KeyboardShortcut.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'phabricator-keyboard-shortcut-manager',
    ),
    'disk' => '/rsrc/js/application/core/KeyboardShortcut.js',
  ),
  'phabricator-keyboard-shortcut-manager' =>
  array(
    'uri' => '/res/04767571/rsrc/js/application/core/KeyboardShortcutManager.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
      3 => 'javelin-dom',
      4 => 'javelin-vector',
    ),
    'disk' => '/rsrc/js/application/core/KeyboardShortcutManager.js',
  ),
  'phabricator-object-selector-css' =>
  array(
    'uri' => '/res/608461d2/rsrc/css/application/objectselector/object-selector.css',
    'type' => 'css',
    'requires' =>
    array(
      0 => 'aphront-dialog-view-css',
    ),
    'disk' => '/rsrc/css/application/objectselector/object-selector.css',
  ),
  'phabricator-prefab' =>
  array(
    'uri' => '/res/5784a112/rsrc/js/application/core/Prefab.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/Prefab.js',
  ),
  'phabricator-profile-css' =>
  array(
    'uri' => '/res/ebe1ac2f/rsrc/css/application/profile/profile-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/profile/profile-view.css',
  ),
  'phabricator-remarkup-css' =>
  array(
    'uri' => '/res/78f26382/rsrc/css/core/remarkup.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/core/remarkup.css',
  ),
  'phabricator-search-results-css' =>
  array(
    'uri' => '/res/f8a86e27/rsrc/css/application/search/search-results.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/search/search-results.css',
  ),
  'phabricator-shaped-request' =>
  array(
    'uri' => '/res/ee0667c4/rsrc/js/application/core/ShapedRequest.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-request',
    ),
    'disk' => '/rsrc/js/application/core/ShapedRequest.js',
  ),
  'phabricator-slowvote-css' =>
  array(
    'uri' => '/res/94d20443/rsrc/css/application/slowvote/slowvote.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/slowvote/slowvote.css',
  ),
  'phabricator-standard-page-view' =>
  array(
    'uri' => '/res/7f5b185e/rsrc/css/application/base/standard-page-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/base/standard-page-view.css',
  ),
  'phabricator-ui-example-css' =>
  array(
    'uri' => '/res/0cef078b/rsrc/css/application/uiexample/example.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/uiexample/example.css',
  ),
  'phabricator-uiexample-javelin-view' =>
  array(
    'uri' => '/res/a2ce2cfc/rsrc/js/application/uiexample/JavelinViewExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/uiexample/JavelinViewExample.js',
  ),
  'phabricator-uiexample-reactor-button' =>
  array(
    'uri' => '/res/142127f6/rsrc/js/application/uiexample/ReactorButtonExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-reactor-dom',
    ),
    'disk' => '/rsrc/js/application/uiexample/ReactorButtonExample.js',
  ),
  'phabricator-uiexample-reactor-checkbox' =>
  array(
    'uri' => '/res/c75cb9e9/rsrc/js/application/uiexample/ReactorCheckboxExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-reactor-dom',
    ),
    'disk' => '/rsrc/js/application/uiexample/ReactorCheckboxExample.js',
  ),
  'phabricator-uiexample-reactor-focus' =>
  array(
    'uri' => '/res/3cc992eb/rsrc/js/application/uiexample/ReactorFocusExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-reactor-dom',
    ),
    'disk' => '/rsrc/js/application/uiexample/ReactorFocusExample.js',
  ),
  'phabricator-uiexample-reactor-input' =>
  array(
    'uri' => '/res/4953da16/rsrc/js/application/uiexample/ReactorInputExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-reactor-dom',
      5 => 'javelin-view-html',
      6 => 'javelin-view-interpreter',
      7 => 'javelin-view-renderer',
    ),
    'disk' => '/rsrc/js/application/uiexample/ReactorInputExample.js',
  ),
  'phabricator-uiexample-reactor-mouseover' =>
  array(
    'uri' => '/res/52a355b6/rsrc/js/application/uiexample/ReactorMouseoverExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-reactor-dom',
    ),
    'disk' => '/rsrc/js/application/uiexample/ReactorMouseoverExample.js',
  ),
  'phabricator-uiexample-reactor-radio' =>
  array(
    'uri' => '/res/ae87f3af/rsrc/js/application/uiexample/ReactorRadioExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-reactor-dom',
    ),
    'disk' => '/rsrc/js/application/uiexample/ReactorRadioExample.js',
  ),
  'phabricator-uiexample-reactor-select' =>
  array(
    'uri' => '/res/23cb448a/rsrc/js/application/uiexample/ReactorSelectExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-reactor-dom',
    ),
    'disk' => '/rsrc/js/application/uiexample/ReactorSelectExample.js',
  ),
  'phabricator-uiexample-reactor-sendclass' =>
  array(
    'uri' => '/res/8cd34264/rsrc/js/application/uiexample/ReactorSendClassExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-reactor-dom',
    ),
    'disk' => '/rsrc/js/application/uiexample/ReactorSendClassExample.js',
  ),
  'phabricator-uiexample-reactor-sendproperties' =>
  array(
    'uri' => '/res/18af54aa/rsrc/js/application/uiexample/ReactorSendPropertiesExample.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-view',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-reactor-dom',
    ),
    'disk' => '/rsrc/js/application/uiexample/ReactorSendPropertiesExample.js',
  ),
  'phriction-document-css' =>
  array(
    'uri' => '/res/8d09bd7f/rsrc/css/application/phriction/phriction-document-css.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/phriction/phriction-document-css.css',
  ),
  'project-edit-css' =>
  array(
    'uri' => '/res/c192b5f9/rsrc/css/application/projects/project-edit.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/projects/project-edit.css',
  ),
  'syntax-highlighting-css' =>
  array(
    'uri' => '/res/5669beb6/rsrc/css/core/syntax.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/core/syntax.css',
  ),
), array(
  'packages' =>
  array(
    '03ef179e' =>
    array(
      'name' => 'diffusion.pkg.css',
      'symbols' =>
      array(
        0 => 'diffusion-commit-view-css',
      ),
      'uri' => '/res/pkg/03ef179e/diffusion.pkg.css',
      'type' => 'css',
    ),
    '4e7acf1a' =>
    array(
      'name' => 'core.pkg.js',
      'symbols' =>
      array(
        0 => 'javelin-mask',
        1 => 'javelin-workflow',
        2 => 'javelin-behavior-workflow',
        3 => 'javelin-behavior-aphront-form-disable-on-submit',
        4 => 'phabricator-keyboard-shortcut-manager',
        5 => 'phabricator-keyboard-shortcut',
        6 => 'javelin-behavior-phabricator-keyboard-shortcuts',
        7 => 'javelin-behavior-refresh-csrf',
        8 => 'javelin-behavior-phabricator-watch-anchor',
      ),
      'uri' => '/res/pkg/4e7acf1a/core.pkg.js',
      'type' => 'js',
    ),
    'aa531d70' =>
    array(
      'name' => 'core.pkg.css',
      'symbols' =>
      array(
        0 => 'phabricator-core-css',
        1 => 'phabricator-core-buttons-css',
        2 => 'phabricator-standard-page-view',
        3 => 'aphront-dialog-view-css',
        4 => 'aphront-form-view-css',
        5 => 'aphront-panel-view-css',
        6 => 'aphront-side-nav-view-css',
        7 => 'aphront-table-view-css',
        8 => 'aphront-crumbs-view-css',
        9 => 'aphront-tokenizer-control-css',
        10 => 'aphront-typeahead-control-css',
        11 => 'aphront-list-filter-view-css',
        12 => 'phabricator-directory-css',
        13 => 'phabricator-remarkup-css',
        14 => 'syntax-highlighting-css',
      ),
      'uri' => '/res/pkg/aa531d70/core.pkg.css',
      'type' => 'css',
    ),
    'b164acea' =>
    array(
      'name' => 'javelin.pkg.js',
      'symbols' =>
      array(
        0 => 'javelin-util',
        1 => 'javelin-install',
        2 => 'javelin-event',
        3 => 'javelin-stratcom',
        4 => 'javelin-behavior',
        5 => 'javelin-request',
        6 => 'javelin-vector',
        7 => 'javelin-dom',
        8 => 'javelin-json',
        9 => 'javelin-uri',
      ),
      'uri' => '/res/pkg/b164acea/javelin.pkg.js',
      'type' => 'js',
    ),
    'bbe7e6f7' =>
    array(
      'name' => 'typeahead.pkg.js',
      'symbols' =>
      array(
        0 => 'javelin-typeahead',
        1 => 'javelin-typeahead-normalizer',
        2 => 'javelin-typeahead-source',
        3 => 'javelin-typeahead-preloaded-source',
        4 => 'javelin-typeahead-ondemand-source',
        5 => 'javelin-tokenizer',
        6 => 'javelin-behavior-aphront-basic-tokenizer',
      ),
      'uri' => '/res/pkg/bbe7e6f7/typeahead.pkg.js',
      'type' => 'js',
    ),
    'e4f8b52c' =>
    array(
      'name' => 'differential.pkg.css',
      'symbols' =>
      array(
        0 => 'differential-core-view-css',
        1 => 'differential-changeset-view-css',
        2 => 'differential-revision-detail-css',
        3 => 'differential-revision-history-css',
        4 => 'differential-table-of-contents-css',
        5 => 'differential-revision-comment-css',
        6 => 'differential-revision-add-comment-css',
        7 => 'differential-revision-comment-list-css',
        8 => 'phabricator-object-selector-css',
        9 => 'aphront-headsup-action-list-view-css',
        10 => 'phabricator-content-source-view-css',
        11 => 'differential-local-commits-view-css',
      ),
      'uri' => '/res/pkg/e4f8b52c/differential.pkg.css',
      'type' => 'css',
    ),
    'ffc38d9a' =>
    array(
      'name' => 'differential.pkg.js',
      'symbols' =>
      array(
        0 => 'phabricator-drag-and-drop-file-upload',
        1 => 'phabricator-shaped-request',
        2 => 'javelin-behavior-differential-feedback-preview',
        3 => 'javelin-behavior-differential-edit-inline-comments',
        4 => 'javelin-behavior-differential-populate',
        5 => 'javelin-behavior-differential-show-more',
        6 => 'javelin-behavior-differential-diff-radios',
        7 => 'javelin-behavior-differential-accept-with-errors',
        8 => 'javelin-behavior-differential-comment-jump',
        9 => 'javelin-behavior-differential-add-reviewers-and-ccs',
        10 => 'javelin-behavior-differential-keyboard-navigation',
        11 => 'javelin-behavior-aphront-drag-and-drop-textarea',
        12 => 'javelin-behavior-phabricator-object-selector',
        13 => 'differential-inline-comment-editor',
      ),
      'uri' => '/res/pkg/ffc38d9a/differential.pkg.js',
      'type' => 'js',
    ),
  ),
  'reverse' =>
  array(
    'aphront-crumbs-view-css' => 'aa531d70',
    'aphront-dialog-view-css' => 'aa531d70',
    'aphront-form-view-css' => 'aa531d70',
    'aphront-headsup-action-list-view-css' => 'e4f8b52c',
    'aphront-list-filter-view-css' => 'aa531d70',
    'aphront-panel-view-css' => 'aa531d70',
    'aphront-side-nav-view-css' => 'aa531d70',
    'aphront-table-view-css' => 'aa531d70',
    'aphront-tokenizer-control-css' => 'aa531d70',
    'aphront-typeahead-control-css' => 'aa531d70',
    'differential-changeset-view-css' => 'e4f8b52c',
    'differential-core-view-css' => 'e4f8b52c',
    'differential-inline-comment-editor' => 'ffc38d9a',
    'differential-local-commits-view-css' => 'e4f8b52c',
    'differential-revision-add-comment-css' => 'e4f8b52c',
    'differential-revision-comment-css' => 'e4f8b52c',
    'differential-revision-comment-list-css' => 'e4f8b52c',
    'differential-revision-detail-css' => 'e4f8b52c',
    'differential-revision-history-css' => 'e4f8b52c',
    'differential-table-of-contents-css' => 'e4f8b52c',
    'diffusion-commit-view-css' => '03ef179e',
    'javelin-behavior' => 'b164acea',
    'javelin-behavior-aphront-basic-tokenizer' => 'bbe7e6f7',
    'javelin-behavior-aphront-drag-and-drop-textarea' => 'ffc38d9a',
    'javelin-behavior-aphront-form-disable-on-submit' => '4e7acf1a',
    'javelin-behavior-differential-accept-with-errors' => 'ffc38d9a',
    'javelin-behavior-differential-add-reviewers-and-ccs' => 'ffc38d9a',
    'javelin-behavior-differential-comment-jump' => 'ffc38d9a',
    'javelin-behavior-differential-diff-radios' => 'ffc38d9a',
    'javelin-behavior-differential-edit-inline-comments' => 'ffc38d9a',
    'javelin-behavior-differential-feedback-preview' => 'ffc38d9a',
    'javelin-behavior-differential-keyboard-navigation' => 'ffc38d9a',
    'javelin-behavior-differential-populate' => 'ffc38d9a',
    'javelin-behavior-differential-show-more' => 'ffc38d9a',
    'javelin-behavior-phabricator-keyboard-shortcuts' => '4e7acf1a',
    'javelin-behavior-phabricator-object-selector' => 'ffc38d9a',
    'javelin-behavior-phabricator-watch-anchor' => '4e7acf1a',
    'javelin-behavior-refresh-csrf' => '4e7acf1a',
    'javelin-behavior-workflow' => '4e7acf1a',
    'javelin-dom' => 'b164acea',
    'javelin-event' => 'b164acea',
    'javelin-install' => 'b164acea',
    'javelin-json' => 'b164acea',
    'javelin-mask' => '4e7acf1a',
    'javelin-request' => 'b164acea',
    'javelin-stratcom' => 'b164acea',
    'javelin-tokenizer' => 'bbe7e6f7',
    'javelin-typeahead' => 'bbe7e6f7',
    'javelin-typeahead-normalizer' => 'bbe7e6f7',
    'javelin-typeahead-ondemand-source' => 'bbe7e6f7',
    'javelin-typeahead-preloaded-source' => 'bbe7e6f7',
    'javelin-typeahead-source' => 'bbe7e6f7',
    'javelin-uri' => 'b164acea',
    'javelin-util' => 'b164acea',
    'javelin-vector' => 'b164acea',
    'javelin-workflow' => '4e7acf1a',
    'phabricator-content-source-view-css' => 'e4f8b52c',
    'phabricator-core-buttons-css' => 'aa531d70',
    'phabricator-core-css' => 'aa531d70',
    'phabricator-directory-css' => 'aa531d70',
    'phabricator-drag-and-drop-file-upload' => 'ffc38d9a',
    'phabricator-keyboard-shortcut' => '4e7acf1a',
    'phabricator-keyboard-shortcut-manager' => '4e7acf1a',
    'phabricator-object-selector-css' => 'e4f8b52c',
    'phabricator-remarkup-css' => 'aa531d70',
    'phabricator-shaped-request' => 'ffc38d9a',
    'phabricator-standard-page-view' => 'aa531d70',
    'syntax-highlighting-css' => 'aa531d70',
  ),
));
