<?php

/**
 * This file is automatically generated. Use 'celerity_mapper.php' to rebuild
 * it.
 * @generated
 */

celerity_register_resource_map(array(
  'aphront-attached-file-view-css' =>
  array(
    'uri' => '/res/a6ca5487/rsrc/css/aphront/attached-file-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/attached-file-view.css',
  ),
  'aphront-calendar-view-css' =>
  array(
    'uri' => '/res/c86d9a4b/rsrc/css/aphront/calendar-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/calendar-view.css',
  ),
  'aphront-contextbar-view-css' =>
  array(
    'uri' => '/res/3e2f3045/rsrc/css/aphront/context-bar.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/context-bar.css',
  ),
  'aphront-crumbs-view-css' =>
  array(
    'uri' => '/res/9009e6bd/rsrc/css/aphront/crumbs-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/crumbs-view.css',
  ),
  'aphront-dark-console-css' =>
  array(
    'uri' => '/res/1a9f84bb/rsrc/css/aphront/dark-console.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/dark-console.css',
  ),
  'aphront-dialog-view-css' =>
  array(
    'uri' => '/res/1c0a5f75/rsrc/css/aphront/dialog-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/dialog-view.css',
  ),
  'aphront-error-view-css' =>
  array(
    'uri' => '/res/e4c5e4ed/rsrc/css/aphront/error-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/error-view.css',
  ),
  'aphront-form-view-css' =>
  array(
    'uri' => '/res/c79fd668/rsrc/css/aphront/form-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/form-view.css',
  ),
  'aphront-headsup-action-list-view-css' =>
  array(
    'uri' => '/res/84743e20/rsrc/css/aphront/headsup-action-list-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/headsup-action-list-view.css',
  ),
  'aphront-list-filter-view-css' =>
  array(
    'uri' => '/res/0f5ddaba/rsrc/css/aphront/list-filter-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/list-filter-view.css',
  ),
  'aphront-pager-view-css' =>
  array(
    'uri' => '/res/43fb79f0/rsrc/css/aphront/pager-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/pager-view.css',
  ),
  'aphront-panel-view-css' =>
  array(
    'uri' => '/res/58da9c70/rsrc/css/aphront/panel-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/panel-view.css',
  ),
  'aphront-request-failure-view-css' =>
  array(
    'uri' => '/res/c9a43002/rsrc/css/aphront/request-failure-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/request-failure-view.css',
  ),
  'aphront-side-nav-view-css' =>
  array(
    'uri' => '/res/f92966bd/rsrc/css/aphront/side-nav-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/side-nav-view.css',
  ),
  'aphront-table-view-css' =>
  array(
    'uri' => '/res/f4f39a2e/rsrc/css/aphront/table-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/table-view.css',
  ),
  'aphront-tokenizer-control-css' =>
  array(
    'uri' => '/res/f530af47/rsrc/css/aphront/tokenizer.css',
    'type' => 'css',
    'requires' =>
    array(
      0 => 'aphront-typeahead-control-css',
    ),
    'disk' => '/rsrc/css/aphront/tokenizer.css',
  ),
  'aphront-typeahead-control-css' =>
  array(
    'uri' => '/res/a05236a6/rsrc/css/aphront/typeahead.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/aphront/typeahead.css',
  ),
  'differential-changeset-view-css' =>
  array(
    'uri' => '/res/59279999/rsrc/css/application/differential/changeset-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/changeset-view.css',
  ),
  'differential-core-view-css' =>
  array(
    'uri' => '/res/438fe316/rsrc/css/application/differential/core.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/core.css',
  ),
  'differential-inline-comment-editor' =>
  array(
    'uri' => '/res/5e4f0aa4/rsrc/js/application/differential/DifferentialInlineCommentEditor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-dom',
      1 => 'javelin-workflow',
      2 => 'javelin-util',
      3 => 'javelin-stratcom',
      4 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/application/differential/DifferentialInlineCommentEditor.js',
  ),
  'differential-revision-add-comment-css' =>
  array(
    'uri' => '/res/849748d3/rsrc/css/application/differential/add-comment.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/add-comment.css',
  ),
  'differential-revision-comment-css' =>
  array(
    'uri' => '/res/9fb8013b/rsrc/css/application/differential/revision-comment.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/revision-comment.css',
  ),
  'differential-revision-comment-list-css' =>
  array(
    'uri' => '/res/3b31faa3/rsrc/css/application/differential/revision-comment-list.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/revision-comment-list.css',
  ),
  'differential-revision-detail-css' =>
  array(
    'uri' => '/res/015e5995/rsrc/css/application/differential/revision-detail.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/revision-detail.css',
  ),
  'differential-revision-history-css' =>
  array(
    'uri' => '/res/0d7d515d/rsrc/css/application/differential/revision-history.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/revision-history.css',
  ),
  'differential-table-of-contents-css' =>
  array(
    'uri' => '/res/d173445b/rsrc/css/application/differential/table-of-contents.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/differential/table-of-contents.css',
  ),
  'diffusion-commit-view-css' =>
  array(
    'uri' => '/res/bc39d876/rsrc/css/application/diffusion/commit-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/diffusion/commit-view.css',
  ),
  'diffusion-source-css' =>
  array(
    'uri' => '/res/db4566b6/rsrc/css/application/diffusion/diffusion-source.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/diffusion/diffusion-source.css',
  ),
  'files-css' =>
  array(
    'uri' => '/res/a265a77d/rsrc/css/application/files/files.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/files/files.css',
  ),
  'herald-css' =>
  array(
    'uri' => '/res/5051f3ab/rsrc/css/application/herald/herald.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/herald/herald.css',
  ),
  'herald-rule-editor' =>
  array(
    'uri' => '/res/4d6dff2b/rsrc/js/application/herald/HeraldRuleEditor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'multirow-row-manager',
      1 => 'javelin-install',
      2 => 'javelin-typeahead',
      3 => 'javelin-util',
      4 => 'javelin-dom',
      5 => 'javelin-tokenizer',
      6 => 'javelin-typeahead-preloaded-source',
      7 => 'javelin-stratcom',
      8 => 'javelin-json',
      9 => 'phabricator-prefab',
    ),
    'disk' => '/rsrc/js/application/herald/HeraldRuleEditor.js',
  ),
  'herald-test-css' =>
  array(
    'uri' => '/res/c0cd6bdb/rsrc/css/application/herald/herald-test.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/herald/herald-test.css',
  ),
  'javelin-behavior' =>
  array(
    'uri' => '/res/24ce4647/rsrc/js/javelin/lib/behavior.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-magical-init',
    ),
    'disk' => '/rsrc/js/javelin/lib/behavior.js',
  ),
  'javelin-behavior-aphront-basic-tokenizer' =>
  array(
    'uri' => '/res/5e183bd5/rsrc/js/application/core/behavior-tokenizer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-typeahead',
      2 => 'javelin-tokenizer',
      3 => 'javelin-typeahead-preloaded-source',
      4 => 'javelin-dom',
      5 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-tokenizer.js',
  ),
  'javelin-behavior-aphront-drag-and-drop' =>
  array(
    'uri' => '/res/ac21045a/rsrc/js/application/core/behavior-drag-and-drop.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
      3 => 'phabricator-drag-and-drop-file-upload',
    ),
    'disk' => '/rsrc/js/application/core/behavior-drag-and-drop.js',
  ),
  'javelin-behavior-aphront-drag-and-drop-textarea' =>
  array(
    'uri' => '/res/fa7527f9/rsrc/js/application/core/behavior-drag-and-drop-textarea.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'phabricator-drag-and-drop-file-upload',
    ),
    'disk' => '/rsrc/js/application/core/behavior-drag-and-drop-textarea.js',
  ),
  'javelin-behavior-aphront-form-disable-on-submit' =>
  array(
    'uri' => '/res/6c659ede/rsrc/js/application/core/behavior-form.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-form.js',
  ),
  'javelin-behavior-countdown-timer' =>
  array(
    'uri' => '/res/5ee9cb13/rsrc/js/application/countdown/timer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/countdown/timer.js',
  ),
  'javelin-behavior-dark-console' =>
  array(
    'uri' => '/res/c80156c4/rsrc/js/application/core/behavior-dark-console.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-util',
      3 => 'javelin-dom',
      4 => 'javelin-request',
      5 => 'phabricator-keyboard-shortcut',
    ),
    'disk' => '/rsrc/js/application/core/behavior-dark-console.js',
  ),
  'javelin-behavior-differential-accept-with-errors' =>
  array(
    'uri' => '/res/41c4685b/rsrc/js/application/differential/behavior-accept-with-errors.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-accept-with-errors.js',
  ),
  'javelin-behavior-differential-add-reviewers-and-ccs' =>
  array(
    'uri' => '/res/fc352745/rsrc/js/application/differential/behavior-add-reviewers-and-ccs.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-tokenizer',
      3 => 'javelin-typeahead',
      4 => 'javelin-typeahead-preloaded-source',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-add-reviewers-and-ccs.js',
  ),
  'javelin-behavior-differential-comment-jump' =>
  array(
    'uri' => '/res/be77fced/rsrc/js/application/differential/behavior-comment-jump.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-util',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-comment-jump.js',
  ),
  'javelin-behavior-differential-diff-radios' =>
  array(
    'uri' => '/res/004cb66f/rsrc/js/application/differential/behavior-diff-radios.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-diff-radios.js',
  ),
  'javelin-behavior-differential-edit-inline-comments' =>
  array(
    'uri' => '/res/9d4ca5d7/rsrc/js/application/differential/behavior-edit-inline-comments.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
      3 => 'javelin-util',
      4 => 'javelin-vector',
      5 => 'differential-inline-comment-editor',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-edit-inline-comments.js',
  ),
  'javelin-behavior-differential-feedback-preview' =>
  array(
    'uri' => '/res/cb399257/rsrc/js/application/differential/behavior-comment-preview.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
      3 => 'javelin-request',
      4 => 'javelin-util',
      5 => 'phabricator-shaped-request',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-comment-preview.js',
  ),
  'javelin-behavior-differential-keyboard-navigation' =>
  array(
    'uri' => '/res/e36415a2/rsrc/js/application/differential/behavior-keyboard-nav.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'phabricator-keyboard-shortcut',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-keyboard-nav.js',
  ),
  'javelin-behavior-differential-populate' =>
  array(
    'uri' => '/res/6efe5cd2/rsrc/js/application/differential/behavior-populate.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-workflow',
      2 => 'javelin-util',
      3 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-populate.js',
  ),
  'javelin-behavior-differential-show-all-comments' =>
  array(
    'uri' => '/res/bcc990f0/rsrc/js/application/differential/behavior-show-all-comments.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-show-all-comments.js',
  ),
  'javelin-behavior-differential-show-more' =>
  array(
    'uri' => '/res/eaaccd7a/rsrc/js/application/differential/behavior-show-more.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-workflow',
      3 => 'javelin-util',
      4 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/application/differential/behavior-show-more.js',
  ),
  'javelin-behavior-diffusion-jump-to' =>
  array(
    'uri' => '/res/7c42e1ba/rsrc/js/application/diffusion/behavior-jump-to.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-util',
      2 => 'javelin-vector',
      3 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/diffusion/behavior-jump-to.js',
  ),
  'javelin-behavior-diffusion-pull-lastmodified' =>
  array(
    'uri' => '/res/29fe2790/rsrc/js/application/diffusion/behavior-pull-lastmodified.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
      3 => 'javelin-request',
    ),
    'disk' => '/rsrc/js/application/diffusion/behavior-pull-lastmodified.js',
  ),
  'javelin-behavior-error-log' =>
  array(
    'uri' => '/res/a5cb42a5/rsrc/js/application/core/behavior-error-log.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-error-log.js',
  ),
  'javelin-behavior-files-drag-and-drop' =>
  array(
    'uri' => '/res/0e84cc42/rsrc/js/application/core/behavior-files-drag-and-drop.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-uri',
      3 => 'phabricator-drag-and-drop-file-upload',
    ),
    'disk' => '/rsrc/js/application/core/behavior-files-drag-and-drop.js',
  ),
  'javelin-behavior-herald-rule-editor' =>
  array(
    'uri' => '/res/77a0c945/rsrc/js/application/herald/herald-rule-editor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'herald-rule-editor',
      1 => 'javelin-behavior',
    ),
    'disk' => '/rsrc/js/application/herald/herald-rule-editor.js',
  ),
  'javelin-behavior-maniphest-project-create' =>
  array(
    'uri' => '/res/85a0eaf9/rsrc/js/application/maniphest/behavior-project-create.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-stratcom',
      3 => 'javelin-workflow',
    ),
    'disk' => '/rsrc/js/application/maniphest/behavior-project-create.js',
  ),
  'javelin-behavior-maniphest-transaction-controls' =>
  array(
    'uri' => '/res/94a2a395/rsrc/js/application/maniphest/behavior-transaction-controls.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-tokenizer',
      3 => 'javelin-typeahead',
      4 => 'javelin-typeahead-preloaded-source',
    ),
    'disk' => '/rsrc/js/application/maniphest/behavior-transaction-controls.js',
  ),
  'javelin-behavior-maniphest-transaction-expand' =>
  array(
    'uri' => '/res/966410de/rsrc/js/application/maniphest/behavior-transaction-expand.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-workflow',
      3 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/application/maniphest/behavior-transaction-expand.js',
  ),
  'javelin-behavior-maniphest-transaction-preview' =>
  array(
    'uri' => '/res/34e22038/rsrc/js/application/maniphest/behavior-transaction-preview.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
      3 => 'phabricator-shaped-request',
    ),
    'disk' => '/rsrc/js/application/maniphest/behavior-transaction-preview.js',
  ),
  'javelin-behavior-owners-path-editor' =>
  array(
    'uri' => '/res/9cf78ffc/rsrc/js/application/owners/owners-path-editor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'owners-path-editor',
      1 => 'javelin-behavior',
    ),
    'disk' => '/rsrc/js/application/owners/owners-path-editor.js',
  ),
  'javelin-behavior-phabricator-keyboard-shortcuts' =>
  array(
    'uri' => '/res/94b009e2/rsrc/js/application/core/behavior-keyboard-shortcuts.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-workflow',
      2 => 'javelin-json',
      3 => 'phabricator-keyboard-shortcut',
    ),
    'disk' => '/rsrc/js/application/core/behavior-keyboard-shortcuts.js',
  ),
  'javelin-behavior-phabricator-object-selector' =>
  array(
    'uri' => '/res/1f7867ca/rsrc/js/application/core/behavior-object-selector.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-request',
      3 => 'javelin-util',
      4 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-object-selector.js',
  ),
  'javelin-behavior-phabricator-watch-anchor' =>
  array(
    'uri' => '/res/46298448/rsrc/js/application/core/behavior-watch-anchor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-util',
      3 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-watch-anchor.js',
  ),
  'javelin-behavior-phriction-document-preview' =>
  array(
    'uri' => '/res/f1665ecd/rsrc/js/application/phriction/phriction-document-preview.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-dom',
      2 => 'javelin-util',
      3 => 'phabricator-shaped-request',
    ),
    'disk' => '/rsrc/js/application/phriction/phriction-document-preview.js',
  ),
  'javelin-behavior-projects-resource-editor' =>
  array(
    'uri' => '/res/a54d5616/rsrc/js/application/projects/projects-resource-editor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'phabricator-prefab',
      2 => 'multirow-row-manager',
      3 => 'javelin-tokenizer',
      4 => 'javelin-typeahead-preloaded-source',
      5 => 'javelin-typeahead',
      6 => 'javelin-dom',
      7 => 'javelin-json',
      8 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/projects/projects-resource-editor.js',
  ),
  0 =>
  array(
    'uri' => '/res/1da00bfe/rsrc/js/javelin/lib/__tests__/URI.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-uri',
      1 => 'javelin-php-serializer',
    ),
    'disk' => '/rsrc/js/javelin/lib/__tests__/URI.js',
  ),
  'javelin-behavior-refresh-csrf' =>
  array(
    'uri' => '/res/88beba4c/rsrc/js/application/core/behavior-refresh-csrf.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-request',
      1 => 'javelin-behavior',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/behavior-refresh-csrf.js',
  ),
  'javelin-behavior-workflow' =>
  array(
    'uri' => '/res/079f49c3/rsrc/js/application/core/behavior-workflow.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-behavior',
      1 => 'javelin-stratcom',
      2 => 'javelin-workflow',
    ),
    'disk' => '/rsrc/js/application/core/behavior-workflow.js',
  ),
  'javelin-color' =>
  array(
    'uri' => '/res/b0439fc9/rsrc/js/javelin/ext/fx/Color.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/ext/fx/Color.js',
  ),
  'javelin-dom' =>
  array(
    'uri' => '/res/0fb82146/rsrc/js/javelin/lib/DOM.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-magical-init',
      1 => 'javelin-install',
      2 => 'javelin-util',
      3 => 'javelin-vector',
      4 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/javelin/lib/DOM.js',
  ),
  'javelin-dynval' =>
  array(
    'uri' => '/res/d89c6f88/rsrc/js/javelin/ext/reactor/core/DynVal.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-reactornode',
      2 => 'javelin-util',
      3 => 'javelin-reactor',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/core/DynVal.js',
  ),
  'javelin-event' =>
  array(
    'uri' => '/res/f14f00d7/rsrc/js/javelin/core/Event.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/core/Event.js',
  ),
  'javelin-fx' =>
  array(
    'uri' => '/res/2b609814/rsrc/js/javelin/ext/fx/FX.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-color',
      1 => 'javelin-install',
      2 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/fx/FX.js',
  ),
  'javelin-install' =>
  array(
    'uri' => '/res/a7a57bf8/rsrc/js/javelin/core/install.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-util',
      1 => 'javelin-magical-init',
    ),
    'disk' => '/rsrc/js/javelin/core/install.js',
  ),
  'javelin-json' =>
  array(
    'uri' => '/res/561b8056/rsrc/js/javelin/lib/JSON.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/lib/JSON.js',
  ),
  'javelin-magical-init' =>
  array(
    'uri' => '/res/6a069362/rsrc/js/javelin/core/init.js',
    'type' => 'js',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/js/javelin/core/init.js',
  ),
  'javelin-mask' =>
  array(
    'uri' => '/res/03ef78b8/rsrc/js/javelin/lib/Mask.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-vector',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/javelin/lib/Mask.js',
  ),
  'javelin-reactor' =>
  array(
    'uri' => '/res/64d41874/rsrc/js/javelin/ext/reactor/core/Reactor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-dynval',
      2 => 'javelin-reactornode',
      3 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/core/Reactor.js',
  ),
  'javelin-reactor-dom' =>
  array(
    'uri' => '/res/d8ab6a5f/rsrc/js/javelin/ext/reactor/dom/RDOM.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-dom',
      1 => 'javelin-dynval',
      2 => 'javelin-reactornode',
      3 => 'javelin-install',
      4 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/dom/RDOM.js',
  ),
  'javelin-reactor-node-calmer' =>
  array(
    'uri' => '/res/b8a3ae50/rsrc/js/javelin/ext/reactor/core/ReactorNodeCalmer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-reactor',
      2 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/core/ReactorNodeCalmer.js',
  ),
  'javelin-reactornode' =>
  array(
    'uri' => '/res/f278cc27/rsrc/js/javelin/ext/reactor/core/ReactorNode.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-reactor',
      2 => 'javelin-util',
      3 => 'javelin-reactor-node-calmer',
    ),
    'disk' => '/rsrc/js/javelin/ext/reactor/core/ReactorNode.js',
  ),
  'javelin-request' =>
  array(
    'uri' => '/res/80744b69/rsrc/js/javelin/lib/Request.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-stratcom',
      2 => 'javelin-util',
      3 => 'javelin-behavior',
      4 => 'javelin-json',
    ),
    'disk' => '/rsrc/js/javelin/lib/Request.js',
  ),
  'javelin-resource' =>
  array(
    'uri' => '/res/1ebc5a0d/rsrc/js/javelin/lib/Resource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-magical-init',
      1 => 'javelin-stratcom',
      2 => 'javelin-util',
      3 => 'javelin-uri',
    ),
    'disk' => '/rsrc/js/javelin/lib/Resource.js',
  ),
  'javelin-stratcom' =>
  array(
    'uri' => '/res/da8a2726/rsrc/js/javelin/core/Stratcom.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-event',
      2 => 'javelin-util',
      3 => 'javelin-magical-init',
    ),
    'disk' => '/rsrc/js/javelin/core/Stratcom.js',
  ),
  'javelin-tokenizer' =>
  array(
    'uri' => '/res/5b541fb2/rsrc/js/javelin/lib/control/tokenizer/Tokenizer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-dom',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
      3 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/tokenizer/Tokenizer.js',
  ),
  'javelin-typeahead' =>
  array(
    'uri' => '/res/9169c000/rsrc/js/javelin/lib/control/typeahead/Typeahead.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-dom',
      2 => 'javelin-vector',
      3 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/Typeahead.js',
  ),
  'javelin-typeahead-composite-source' =>
  array(
    'uri' => '/res/7c0d631f/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadCompositeSource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-typeahead-source',
      2 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadCompositeSource.js',
  ),
  'javelin-typeahead-normalizer' =>
  array(
    'uri' => '/res/8b6055d4/rsrc/js/javelin/lib/control/typeahead/normalizer/TypeaheadNormalizer.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/normalizer/TypeaheadNormalizer.js',
  ),
  'javelin-typeahead-ondemand-source' =>
  array(
    'uri' => '/res/d82d7faf/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadOnDemandSource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
      3 => 'javelin-request',
      4 => 'javelin-typeahead-source',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadOnDemandSource.js',
  ),
  'javelin-typeahead-preloaded-source' =>
  array(
    'uri' => '/res/d464efd2/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadPreloadedSource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
      3 => 'javelin-request',
      4 => 'javelin-typeahead-source',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadPreloadedSource.js',
  ),
  'javelin-typeahead-source' =>
  array(
    'uri' => '/res/57299d35/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadSource.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-dom',
      3 => 'javelin-typeahead-normalizer',
    ),
    'disk' => '/rsrc/js/javelin/lib/control/typeahead/source/TypeaheadSource.js',
  ),
  'javelin-uri' =>
  array(
    'uri' => '/res/a6d12b2c/rsrc/js/javelin/lib/URI.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
    ),
    'disk' => '/rsrc/js/javelin/lib/URI.js',
  ),
  'javelin-util' =>
  array(
    'uri' => '/res/21ca8b6c/rsrc/js/javelin/core/util.js',
    'type' => 'js',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/js/javelin/core/util.js',
  ),
  'javelin-vector' =>
  array(
    'uri' => '/res/50535cb8/rsrc/js/javelin/lib/Vector.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-event',
    ),
    'disk' => '/rsrc/js/javelin/lib/Vector.js',
  ),
  'javelin-workflow' =>
  array(
    'uri' => '/res/76fa44f3/rsrc/js/javelin/lib/Workflow.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-stratcom',
      1 => 'javelin-request',
      2 => 'javelin-dom',
      3 => 'javelin-vector',
      4 => 'javelin-install',
      5 => 'javelin-util',
      6 => 'javelin-mask',
      7 => 'javelin-uri',
    ),
    'disk' => '/rsrc/js/javelin/lib/Workflow.js',
  ),
  'mainphest-task-detail-css' =>
  array(
    'uri' => '/res/e2fbb468/rsrc/css/application/maniphest/task-detail.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/maniphest/task-detail.css',
  ),
  'maniphest-task-summary-css' =>
  array(
    'uri' => '/res/14cb4b5d/rsrc/css/application/maniphest/task-summary.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/maniphest/task-summary.css',
  ),
  'maniphest-transaction-detail-css' =>
  array(
    'uri' => '/res/149fccab/rsrc/css/application/maniphest/transaction-detail.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/maniphest/transaction-detail.css',
  ),
  'multirow-row-manager' =>
  array(
    'uri' => '/res/0a9b3dee/rsrc/js/application/core/MultirowRowManager.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-stratcom',
      2 => 'javelin-dom',
      3 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/core/MultirowRowManager.js',
  ),
  'owners-path-editor' =>
  array(
    'uri' => '/res/e6c51eb6/rsrc/js/application/owners/OwnersPathEditor.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'multirow-row-manager',
      1 => 'javelin-install',
      2 => 'path-typeahead',
      3 => 'javelin-dom',
      4 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/owners/OwnersPathEditor.js',
  ),
  'owners-path-editor-css' =>
  array(
    'uri' => '/res/9bc5332c/rsrc/css/application/owners/owners-path-editor.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/owners/owners-path-editor.css',
  ),
  'path-typeahead' =>
  array(
    'uri' => '/res/50246fb6/rsrc/js/application/herald/PathTypeahead.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-typeahead',
      2 => 'javelin-dom',
      3 => 'javelin-request',
      4 => 'javelin-typeahead-ondemand-source',
      5 => 'javelin-util',
    ),
    'disk' => '/rsrc/js/application/herald/PathTypeahead.js',
  ),
  'phabricator-core-buttons-css' =>
  array(
    'uri' => '/res/3059cf79/rsrc/css/core/buttons.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/core/buttons.css',
  ),
  'phabricator-core-css' =>
  array(
    'uri' => '/res/bd20d04b/rsrc/css/core/core.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/core/core.css',
  ),
  'phabricator-countdown-css' =>
  array(
    'uri' => '/res/0f646281/rsrc/css/application/countdown/timer.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/countdown/timer.css',
  ),
  'phabricator-directory-css' =>
  array(
    'uri' => '/res/a3d307c5/rsrc/css/application/directory/phabricator-directory.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/directory/phabricator-directory.css',
  ),
  'phabricator-drag-and-drop-file-upload' =>
  array(
    'uri' => '/res/63a06ad9/rsrc/js/application/core/DragAndDropFileUpload.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-request',
      3 => 'javelin-dom',
      4 => 'javelin-uri',
    ),
    'disk' => '/rsrc/js/application/core/DragAndDropFileUpload.js',
  ),
  'phabricator-feed-css' =>
  array(
    'uri' => '/res/32e5879b/rsrc/css/application/feed/feed.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/feed/feed.css',
  ),
  'phabricator-keyboard-shortcut' =>
  array(
    'uri' => '/res/beed38cd/rsrc/js/application/core/KeyboardShortcut.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'phabricator-keyboard-shortcut-manager',
    ),
    'disk' => '/rsrc/js/application/core/KeyboardShortcut.js',
  ),
  'phabricator-keyboard-shortcut-manager' =>
  array(
    'uri' => '/res/04767571/rsrc/js/application/core/KeyboardShortcutManager.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-stratcom',
      3 => 'javelin-dom',
      4 => 'javelin-vector',
    ),
    'disk' => '/rsrc/js/application/core/KeyboardShortcutManager.js',
  ),
  'phabricator-object-selector-css' =>
  array(
    'uri' => '/res/608461d2/rsrc/css/application/objectselector/object-selector.css',
    'type' => 'css',
    'requires' =>
    array(
      0 => 'aphront-dialog-view-css',
    ),
    'disk' => '/rsrc/css/application/objectselector/object-selector.css',
  ),
  'phabricator-prefab' =>
  array(
    'uri' => '/res/5784a112/rsrc/js/application/core/Prefab.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-dom',
    ),
    'disk' => '/rsrc/js/application/core/Prefab.js',
  ),
  'phabricator-profile-css' =>
  array(
    'uri' => '/res/ebe1ac2f/rsrc/css/application/profile/profile-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/profile/profile-view.css',
  ),
  'phabricator-remarkup-css' =>
  array(
    'uri' => '/res/7ca89111/rsrc/css/core/remarkup.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/core/remarkup.css',
  ),
  'phabricator-search-results-css' =>
  array(
    'uri' => '/res/f8a86e27/rsrc/css/application/search/search-results.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/search/search-results.css',
  ),
  'phabricator-shaped-request' =>
  array(
    'uri' => '/res/ee0667c4/rsrc/js/application/core/ShapedRequest.js',
    'type' => 'js',
    'requires' =>
    array(
      0 => 'javelin-install',
      1 => 'javelin-util',
      2 => 'javelin-request',
    ),
    'disk' => '/rsrc/js/application/core/ShapedRequest.js',
  ),
  'phabricator-slowvote-css' =>
  array(
    'uri' => '/res/94d20443/rsrc/css/application/slowvote/slowvote.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/slowvote/slowvote.css',
  ),
  'phabricator-standard-page-view' =>
  array(
    'uri' => '/res/325b5b0f/rsrc/css/application/base/standard-page-view.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/base/standard-page-view.css',
  ),
  'phabricator-ui-example-css' =>
  array(
    'uri' => '/res/0cef078b/rsrc/css/application/uiexample/example.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/uiexample/example.css',
  ),
  'phriction-document-css' =>
  array(
    'uri' => '/res/a0eb9ea1/rsrc/css/application/phriction/phriction-document-css.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/phriction/phriction-document-css.css',
  ),
  'project-edit-css' =>
  array(
    'uri' => '/res/c192b5f9/rsrc/css/application/projects/project-edit.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/application/projects/project-edit.css',
  ),
  'syntax-highlighting-css' =>
  array(
    'uri' => '/res/14bc2ee1/rsrc/css/core/syntax.css',
    'type' => 'css',
    'requires' =>
    array(
    ),
    'disk' => '/rsrc/css/core/syntax.css',
  ),
), array(
  'packages' =>
  array(
    '03ef179e' =>
    array(
      'name' => 'diffusion.pkg.css',
      'symbols' =>
      array(
        0 => 'diffusion-commit-view-css',
      ),
      'uri' => '/res/pkg/03ef179e/diffusion.pkg.css',
      'type' => 'css',
    ),
    '3dbf4083' =>
    array(
      'name' => 'javelin.pkg.js',
      'symbols' =>
      array(
        0 => 'javelin-util',
        1 => 'javelin-install',
        2 => 'javelin-event',
        3 => 'javelin-stratcom',
        4 => 'javelin-behavior',
        5 => 'javelin-request',
        6 => 'javelin-vector',
        7 => 'javelin-dom',
        8 => 'javelin-json',
        9 => 'javelin-uri',
      ),
      'uri' => '/res/pkg/3dbf4083/javelin.pkg.js',
      'type' => 'js',
    ),
    '3f2092d7' =>
    array(
      'name' => 'differential.pkg.css',
      'symbols' =>
      array(
        0 => 'differential-core-view-css',
        1 => 'differential-changeset-view-css',
        2 => 'differential-revision-detail-css',
        3 => 'differential-revision-history-css',
        4 => 'differential-table-of-contents-css',
        5 => 'differential-revision-comment-css',
        6 => 'differential-revision-add-comment-css',
        7 => 'differential-revision-comment-list-css',
      ),
      'uri' => '/res/pkg/3f2092d7/differential.pkg.css',
      'type' => 'css',
    ),
    '66a154fc' =>
    array(
      'name' => 'differential.pkg.js',
      'symbols' =>
      array(
        0 => 'javelin-behavior-differential-feedback-preview',
        1 => 'javelin-behavior-differential-edit-inline-comments',
        2 => 'javelin-behavior-differential-populate',
        3 => 'javelin-behavior-differential-show-more',
        4 => 'javelin-behavior-differential-diff-radios',
      ),
      'uri' => '/res/pkg/66a154fc/differential.pkg.js',
      'type' => 'js',
    ),
    '95c67dcd' =>
    array(
      'name' => 'workflow.pkg.js',
      'symbols' =>
      array(
        0 => 'javelin-mask',
        1 => 'javelin-workflow',
        2 => 'javelin-behavior-workflow',
        3 => 'javelin-behavior-aphront-form-disable-on-submit',
        4 => 'phabricator-keyboard-shortcut-manager',
        5 => 'phabricator-keyboard-shortcut',
        6 => 'javelin-behavior-phabricator-keyboard-shortcuts',
      ),
      'uri' => '/res/pkg/95c67dcd/workflow.pkg.js',
      'type' => 'js',
    ),
    'ac869011' =>
    array(
      'name' => 'typeahead.pkg.js',
      'symbols' =>
      array(
        0 => 'javelin-typeahead',
        1 => 'javelin-typeahead-normalizer',
        2 => 'javelin-typeahead-source',
        3 => 'javelin-typeahead-preloaded-source',
        4 => 'javelin-typeahead-ondemand-source',
        5 => 'javelin-tokenizer',
        6 => 'javelin-behavior-aphront-basic-tokenizer',
      ),
      'uri' => '/res/pkg/ac869011/typeahead.pkg.js',
      'type' => 'js',
    ),
    70966590 =>
    array(
      'name' => 'core.pkg.css',
      'symbols' =>
      array(
        0 => 'phabricator-core-css',
        1 => 'phabricator-core-buttons-css',
        2 => 'phabricator-standard-page-view',
        3 => 'aphront-dialog-view-css',
        4 => 'aphront-form-view-css',
        5 => 'aphront-panel-view-css',
        6 => 'aphront-side-nav-view-css',
        7 => 'aphront-table-view-css',
        8 => 'aphront-crumbs-view-css',
        9 => 'aphront-tokenizer-control-css',
        10 => 'aphront-typeahead-control-css',
        11 => 'aphront-list-filter-view-css',
        12 => 'phabricator-directory-css',
        13 => 'phabricator-remarkup-css',
        14 => 'syntax-highlighting-css',
      ),
      'uri' => '/res/pkg/70966590/core.pkg.css',
      'type' => 'css',
    ),
  ),
  'reverse' =>
  array(
    'aphront-crumbs-view-css' => '70966590',
    'aphront-dialog-view-css' => '70966590',
    'aphront-form-view-css' => '70966590',
    'aphront-list-filter-view-css' => '70966590',
    'aphront-panel-view-css' => '70966590',
    'aphront-side-nav-view-css' => '70966590',
    'aphront-table-view-css' => '70966590',
    'aphront-tokenizer-control-css' => '70966590',
    'aphront-typeahead-control-css' => '70966590',
    'differential-changeset-view-css' => '3f2092d7',
    'differential-core-view-css' => '3f2092d7',
    'differential-revision-add-comment-css' => '3f2092d7',
    'differential-revision-comment-css' => '3f2092d7',
    'differential-revision-comment-list-css' => '3f2092d7',
    'differential-revision-detail-css' => '3f2092d7',
    'differential-revision-history-css' => '3f2092d7',
    'differential-table-of-contents-css' => '3f2092d7',
    'diffusion-commit-view-css' => '03ef179e',
    'javelin-behavior' => '3dbf4083',
    'javelin-behavior-aphront-basic-tokenizer' => 'ac869011',
    'javelin-behavior-aphront-form-disable-on-submit' => '95c67dcd',
    'javelin-behavior-differential-diff-radios' => '66a154fc',
    'javelin-behavior-differential-edit-inline-comments' => '66a154fc',
    'javelin-behavior-differential-feedback-preview' => '66a154fc',
    'javelin-behavior-differential-populate' => '66a154fc',
    'javelin-behavior-differential-show-more' => '66a154fc',
    'javelin-behavior-phabricator-keyboard-shortcuts' => '95c67dcd',
    'javelin-behavior-workflow' => '95c67dcd',
    'javelin-dom' => '3dbf4083',
    'javelin-event' => '3dbf4083',
    'javelin-install' => '3dbf4083',
    'javelin-json' => '3dbf4083',
    'javelin-mask' => '95c67dcd',
    'javelin-request' => '3dbf4083',
    'javelin-stratcom' => '3dbf4083',
    'javelin-tokenizer' => 'ac869011',
    'javelin-typeahead' => 'ac869011',
    'javelin-typeahead-normalizer' => 'ac869011',
    'javelin-typeahead-ondemand-source' => 'ac869011',
    'javelin-typeahead-preloaded-source' => 'ac869011',
    'javelin-typeahead-source' => 'ac869011',
    'javelin-uri' => '3dbf4083',
    'javelin-util' => '3dbf4083',
    'javelin-vector' => '3dbf4083',
    'javelin-workflow' => '95c67dcd',
    'phabricator-core-buttons-css' => '70966590',
    'phabricator-core-css' => '70966590',
    'phabricator-directory-css' => '70966590',
    'phabricator-keyboard-shortcut' => '95c67dcd',
    'phabricator-keyboard-shortcut-manager' => '95c67dcd',
    'phabricator-remarkup-css' => '70966590',
    'phabricator-standard-page-view' => '70966590',
    'syntax-highlighting-css' => '70966590',
  ),
));
