<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/response/404');
phutil_require_module('phabricator', 'aphront/response/redirect');
phutil_require_module('phabricator', 'applications/people/storage/user');
phutil_require_module('phabricator', 'applications/phame/controller/base');
phutil_require_module('phabricator', 'applications/phame/storage/post');
phutil_require_module('phabricator', 'applications/phame/view/postdetail');
phutil_require_module('phabricator', 'infrastructure/util/slug');
phutil_require_module('phabricator', 'view/form/error');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhamePostViewController.php');
