<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'lint/engine/phutil');

phutil_require_module('phabricator', 'infrastructure/lint/linter/javelin');


phutil_require_source('PhabricatorLintEngine.php');
