<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/people/controller/base');
phutil_require_module('phabricator', 'infrastructure/env');


phutil_require_source('PhabricatorUserSettingsPanelController.php');
