<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/response/ajax');
phutil_require_module('phabricator', 'applications/maniphest/controller/base');
phutil_require_module('phabricator', 'applications/markup/engine');

phutil_require_module('phutil', 'utils');


phutil_require_source('ManiphestTaskDescriptionPreviewController.php');
