<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/drydock/constants/leasestatus');
phutil_require_module('phabricator', 'applications/drydock/storage/base');
phutil_require_module('phabricator', 'applications/drydock/storage/resource');
phutil_require_module('phabricator', 'applications/phid/constants');
phutil_require_module('phabricator', 'applications/phid/storage/phid');

phutil_require_module('phutil', 'utils');


phutil_require_source('DrydockLease.php');
