<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/owners/mail/base');
phutil_require_module('phabricator', 'applications/phid/handle/data');

phutil_require_module('phutil', 'utils');


phutil_require_source('PackageModifyMail.php');
