<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/chatlog/storage/event');
phutil_require_module('phabricator', 'applications/conduit/method/chatlog/base');

phutil_require_module('phutil', 'utils');


phutil_require_source('ConduitAPI_chatlog_record_Method.php');
