<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/differential/field/exception/incomplete');
phutil_require_module('phabricator', 'applications/differential/field/exception/notavailable');
phutil_require_module('phabricator', 'applications/differential/field/exception/parse');
phutil_require_module('phabricator', 'applications/metamta/storage/mailinglist');
phutil_require_module('phabricator', 'applications/people/storage/user');
phutil_require_module('phabricator', 'applications/people/storage/userstatus');
phutil_require_module('phabricator', 'view/utils');

phutil_require_module('phutil', 'utils');


phutil_require_source('DifferentialFieldSpecification.php');
