<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/differential/field/exception/incomplete');
phutil_require_module('phabricator', 'applications/differential/field/exception/notavailable');


phutil_require_source('DifferentialFieldSpecification.php');
